import { useState } from 'react';
import { Link } from 'react-router-dom';
import { apiRequest } from '../../service/api';

export type PaymentStatus='CREATED'|'PENDING'|'SUCCESS'|'FAILED'|'CANCELLED'|'REFUNDED';
export type Payment={id:string;userId:string;swapRequestId:string|null;sessionId:string|null;amount:number;currency:string;status:PaymentStatus;provider:string;providerPaymentId:string|null;providerOrderId:string|null;description:string;createdAt:string;sessionStartAt?:string|null;sessionTimezone?:string|null};
type Checkout={paymentId:string;provider:string;keyId:string;orderId:string;amount:number;currency:string;description:string};
type CheckoutResult={razorpay_payment_id:string;razorpay_order_id:string;razorpay_signature:string};
declare global { interface Window { Razorpay?:new(options:Record<string,unknown>)=>{open:()=>void;on:(event:string,callback:(value:{error?:{reason?:string}})=>void)=>void} } }
export const paymentAmountLabel=(amount:number,currency:string)=>{const fractionDigits=new Intl.NumberFormat(undefined,{style:'currency',currency}).resolvedOptions().maximumFractionDigits ?? 2;return new Intl.NumberFormat(undefined,{style:'currency',currency}).format(amount/(10**fractionDigits));};
const statusText:Record<PaymentStatus,string>={CREATED:'Created',PENDING:'Pending',SUCCESS:'Successful',FAILED:'Failed',CANCELLED:'Cancelled',REFUNDED:'Refunded'};

export function PaymentStatusBadge({status}:{status:PaymentStatus}){const tone=status==='SUCCESS'?'bg-emerald-100 text-emerald-800':status==='FAILED'?'bg-rose-100 text-rose-800':status==='REFUNDED'?'bg-violet-100 text-violet-800':status==='CANCELLED'?'bg-slate-100 text-slate-600':'bg-amber-100 text-amber-800';return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-bold ${tone}`}>{statusText[status]}</span>}

export function PaymentCard({payment}:{payment:Payment}){return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold text-slate-900">{payment.description||'SkillSwap payment'}</p><p className="mt-1 text-xl font-extrabold text-slate-800">{paymentAmountLabel(payment.amount,payment.currency)}</p></div><PaymentStatusBadge status={payment.status}/></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs text-slate-500"><span>{new Date(payment.createdAt).toLocaleString()}</span><span>{payment.providerPaymentId?`Reference ${payment.providerPaymentId}`:`Transaction ${payment.id.slice(0,8)}`}</span></div><div className="mt-3 flex flex-wrap gap-3">{payment.sessionId&&<Link to={`/sessions/${encodeURIComponent(payment.sessionId)}`} className="text-sm font-semibold text-brand-700 hover:underline">View session</Link>}{payment.swapRequestId&&<Link to={`/swap-requests/${encodeURIComponent(payment.swapRequestId)}`} className="text-sm font-semibold text-brand-700 hover:underline">View exchange</Link>}<Link to={`/payments?id=${encodeURIComponent(payment.id)}`} className="text-sm font-semibold text-slate-600 hover:underline">View payment</Link></div></article>}

export function PaymentSummary({amount,currency,description}:{amount:number;currency:string;description:string}){return <div className="rounded-xl bg-brand-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-brand-700">Review amount</p><p className="mt-1 text-2xl font-extrabold text-slate-900">{paymentAmountLabel(amount,currency)}</p><p className="mt-1 text-sm text-slate-600">{description}</p><p className="mt-2 text-xs text-slate-500">Card and payment credentials are handled securely by the payment provider.</p></div>}

export function PaymentEmptyState(){return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><span aria-hidden="true" className="text-3xl">◇</span><h2 className="mt-2 font-bold text-slate-900">No payments yet</h2><p className="mt-1 text-sm text-slate-500">Your session payments will appear here.</p><Link to="/sessions" className="mt-4 inline-flex min-h-10 items-center rounded-lg bg-brand-700 px-4 text-sm font-semibold text-white">View sessions</Link></div>}
export function PaymentSkeleton(){return <div className="animate-pulse space-y-3" aria-label="Loading payments">{[1,2,3].map(id=><div key={id} className="h-28 rounded-2xl bg-slate-200"/>)}</div>}
export function PaymentSuccess(){return <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-900">Payment successful</p>}
export function PaymentFailed({message='Payment failed. Please try again.'}:{message?:string}){return <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{message}</p>}

export function PaymentModal({checkout,busy,onPay,onClose}:{checkout:Checkout;busy:boolean;onPay:()=>void;onClose:()=>void}){return <div role="dialog" aria-modal="true" aria-labelledby="payment-dialog-title" className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-xl"><h2 id="payment-dialog-title" className="text-xl font-extrabold text-slate-900">Review session payment</h2><div className="mt-4"><PaymentSummary amount={checkout.amount} currency={checkout.currency} description={checkout.description}/></div><div className="mt-4 flex justify-end gap-2"><button onClick={onClose} disabled={busy} className="min-h-11 rounded-xl border border-slate-300 px-4 text-sm font-semibold text-slate-700">Cancel</button><button onClick={onPay} disabled={busy} className="min-h-11 rounded-xl bg-brand-700 px-5 text-sm font-bold text-white disabled:opacity-50">{busy?'Opening checkout…':'Pay Now'}</button></div></div></div>}

async function loadCheckoutScript(){if(window.Razorpay)return;await new Promise<void>((resolve,reject)=>{const old=document.querySelector<HTMLScriptElement>('script[data-razorpay-checkout]');if(old){old.addEventListener('load',()=>resolve(),{once:true});old.addEventListener('error',()=>reject(new Error('Checkout could not be loaded.')),{once:true});return;}const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.async=true;script.dataset.razorpayCheckout='true';script.onload=()=>resolve();script.onerror=()=>reject(new Error('Checkout could not be loaded.'));document.head.appendChild(script);});}

export function PaymentButton({sessionId,amount,currency,description,onUpdated}:{sessionId:string;amount:number;currency:string;description:string;onUpdated?:(payment:Payment)=>void}){const [checkout,setCheckout]=useState<Checkout|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<PaymentStatus|null>(null);async function prepare(){setBusy(true);setError('');setResult(null);try{const data=await apiRequest<{checkout:Checkout}>('/api/payments/create',{method:'POST',body:JSON.stringify({sessionId})});setCheckout(data.checkout);}catch(e){setError(e instanceof Error?e.message:'Payment setup failed. Please try again.');}finally{setBusy(false);}}async function pay(){if(!checkout)return;setBusy(true);setError('');try{await loadCheckoutScript();if(!window.Razorpay)throw new Error('Checkout is unavailable. Please try again later.');const modal=new window.Razorpay({key:checkout.keyId,amount:checkout.amount,currency:checkout.currency,name:'SkillSwap',description:checkout.description,order_id:checkout.orderId,handler:async(response:CheckoutResult)=>{try{const verified=await apiRequest<{item:Payment}>('/api/payments/verify',{method:'POST',body:JSON.stringify({paymentId:checkout.paymentId,providerPaymentId:response.razorpay_payment_id,providerOrderId:response.razorpay_order_id,signature:response.razorpay_signature})});setResult(verified.item.status);onUpdated?.(verified.item);setCheckout(null);}catch(e){setError(e instanceof Error?e.message:'Payment verification failed.');setResult('PENDING');}finally{setBusy(false);}},modal:{ondismiss:()=>{setResult('CANCELLED');setBusy(false);setCheckout(null);}}});modal.on('payment.failed',()=>{setResult('FAILED');setError('Payment failed. Please try again.');setBusy(false);setCheckout(null);});modal.open();}catch(e){setError(e instanceof Error?e.message:'Checkout could not be opened.');setBusy(false);}}
  return <div className="space-y-3">{result==='SUCCESS'&&<PaymentSuccess/>}{result==='FAILED'&&<PaymentFailed message={error||'Payment failed. Please try again.'}/ >}{result==='PENDING'&&<p role="status" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Payment is being processed. Refresh payment history to check the verified status.</p>}{result==='CANCELLED'&&<p role="status" className="rounded-xl bg-slate-100 p-3 text-sm text-slate-700">Payment cancelled.</p>}{error&&result!=='FAILED'&&<PaymentFailed message={error}/ >}{!checkout?<button disabled={busy} onClick={()=>void prepare()} className="min-h-11 rounded-xl bg-brand-700 px-5 text-sm font-bold text-white disabled:opacity-50">{busy?'Preparing secure checkout…':result==='FAILED'?'Retry Payment':'Review Amount'}</button>:<PaymentModal checkout={{...checkout,amount,currency,description}} busy={busy} onPay={()=>void pay()} onClose={()=>setCheckout(null)}/>}</div>}

export function PaymentHistory({items}:{items:Payment[]}){return <div className="grid gap-3">{items.map(payment=><PaymentCard key={payment.id} payment={payment}/>)}</div>}
