import { randomUUID } from 'node:crypto';

const statuses = ['PENDING','ACCEPTED','IN_PROGRESS','COMPLETED','REJECTED','CANCELLED'];
const reportStatuses = ['OPEN','UNDER_REVIEW','RESOLVED','DISMISSED'];
const reportReasons = ['Harassment','Spam','Scam','Inappropriate behavior','Fake profile','Suspicious activity','Other'];
const pageArgs = url => {
  const page = Math.max(1, Math.min(100000, Number.parseInt(url.searchParams.get('page') || '1', 10) || 1));
  const limit = Math.max(1, Math.min(100, Number.parseInt(url.searchParams.get('limit') || '20', 10) || 20));
  return {page,limit,offset:(page-1)*limit};
};
const json = value => { try { return JSON.parse(value || '{}'); } catch { return {}; } };
const cleanQuery = value => String(value || '').trim().slice(0,100);
const categoryValid = value => /^[\p{L}\p{N}][\p{L}\p{N} &/+-]{0,49}$/u.test(value);

export async function handleAdminApi({req,res,path,method,url,db,admin,send,randomUUID,auditAdmin,adminNotification,revokeRealtime=()=>{},recommendationMetrics=()=>({}),subscriptionService}) {
  if (method === 'GET' && path === '/api/admin/dashboard') {
    const count=(table,where='')=>Number(db.prepare(`SELECT COUNT(*) AS n FROM ${table} ${where}`).get().n);
    const recentUsers=db.prepare(`SELECT id,name,email,role,status,created_at AS createdAt FROM users ORDER BY created_at DESC LIMIT 5`).all();
    const recentSwaps=db.prepare(`SELECT sr.id,sender.name AS senderName,receiver.name AS receiverName,offered.name AS skillOffered,wanted.name AS skillWanted,COALESCE(sr.workflow_status,sr.status) AS status,sr.created_at AS createdAt FROM swap_requests sr JOIN users sender ON sender.id=sr.sender_id JOIN users receiver ON receiver.id=sr.receiver_id JOIN skills offered ON offered.id=sr.skill_offered_id JOIN skills wanted ON wanted.id=sr.skill_wanted_id ORDER BY sr.created_at DESC LIMIT 5`).all();
    const recentReports=db.prepare(`SELECT r.id,r.reason,r.status,r.created_at AS createdAt,u.name AS reportedUserName FROM reports r LEFT JOIN users u ON u.id=r.reported_user_id ORDER BY r.created_at DESC LIMIT 5`).all();
    const recentPayments=db.prepare(`SELECT p.id,p.amount,p.currency,p.status,p.provider,p.created_at AS createdAt,u.name AS userName,ss.id AS sessionId FROM payments p JOIN users u ON u.id=p.user_id LEFT JOIN skill_sessions ss ON ss.id=p.session_id ORDER BY p.created_at DESC LIMIT 5`).all();
    return send(res,200,{stats:{totalUsers:count('users'),activeUsers:count('users',"WHERE status='active'"),suspendedUsers:count('users',"WHERE status='suspended'"),blockedRelationships:count('user_blocks'),openReports:count('reports',"WHERE status IN ('OPEN','UNDER_REVIEW')"),pendingSwaps:count('swap_requests',"WHERE COALESCE(workflow_status,status)='PENDING'"),cancelledSessions:count('skill_sessions',"WHERE status='CANCELLED'"),newUsers:count('users',"WHERE created_at>=datetime('now','-30 days')"),totalSkills:count('skills'),totalSwapRequests:count('swap_requests'),pendingSwapRequests:count('swap_requests',"WHERE COALESCE(workflow_status,status)='PENDING'"),activeSwaps:count('swap_requests',"WHERE COALESCE(workflow_status,status) IN ('ACCEPTED','IN_PROGRESS')"),completedSwaps:count('swap_requests',"WHERE COALESCE(workflow_status,status)='COMPLETED'"),totalSessions:count('skill_sessions'),upcomingSessions:count('skill_sessions',"WHERE status IN ('PROPOSED','CONFIRMED') AND start_at>=CURRENT_TIMESTAMP"),totalPayments:count('payments'),successfulPayments:count('payments',"WHERE status='SUCCESS'"),failedPayments:count('payments',"WHERE status='FAILED'"),pendingReports:count('reports',"WHERE status IN ('OPEN','UNDER_REVIEW')"),activeSubscriptions:count('subscriptions',"WHERE status='ACTIVE'"),weeklySubscribers:count('subscriptions',"WHERE status='ACTIVE' AND plan='WEEKLY'"),monthlySubscribers:count('subscriptions',"WHERE status='ACTIVE' AND plan='MONTHLY'"),expiredSubscriptions:count('subscriptions',"WHERE status='EXPIRED'"),subscriptionRevenue:Number(db.prepare("SELECT COALESCE(SUM(amount),0) AS n FROM payments WHERE status='SUCCESS' AND metadata LIKE '%\"product\":\"subscription\"%'").get().n),...recommendationMetrics()},recentUsers,recentSwaps,recentReports,recentPayments});
  }
  if (method==='GET' && path==='/api/admin/users') {
    const {page,limit,offset}=pageArgs(url),q=cleanQuery(url.searchParams.get('q')),filter=String(url.searchParams.get('status')||'all').toLowerCase(),sort=String(url.searchParams.get('sort')||'newest').toLowerCase();
    if(!['all','active','suspended','removed','admin'].includes(filter)||!['newest','oldest','name'].includes(sort))return send(res,400,{error:'Choose valid user filters.'});
    const clauses=[],args=[];if(q){clauses.push('(u.name LIKE ? OR u.email LIKE ?)');args.push(`%${q}%`,`%${q}%`);}if(filter==='admin')clauses.push("u.role='admin'");else if(filter==='removed')clauses.push('u.deleted_at IS NOT NULL');else if(filter!=='all')clauses.push('u.deleted_at IS NULL AND u.status=?'),args.push(filter);
    const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:'';const order=sort==='name'?'u.name COLLATE NOCASE,u.id':sort==='oldest'?'u.created_at ASC,u.id':'u.created_at DESC,u.id';
    const total=Number(db.prepare(`SELECT COUNT(*) AS n FROM users u ${where}`).get(...args).n);
    const items=db.prepare(`SELECT u.id,u.name,u.email,u.role,CASE WHEN u.deleted_at IS NOT NULL THEN 'removed' ELSE u.status END AS status,u.deleted_at AS deletedAt,u.created_at AS createdAt,u.suspended_at AS suspendedAt,u.suspension_reason AS suspensionReason,(SELECT ROUND(100.0*sum(v)/8) FROM (SELECT length(trim(u.name))>0 v UNION ALL SELECT length(trim(u.bio))>0 UNION ALL SELECT length(trim(u.college)>0) UNION ALL SELECT length(trim(u.location)>0) UNION ALL SELECT EXISTS(SELECT 1 FROM user_skills us WHERE us.user_id=u.id AND us.type='TEACH') UNION ALL SELECT EXISTS(SELECT 1 FROM user_skills us WHERE us.user_id=u.id AND us.type='LEARN') UNION ALL SELECT length(trim(u.learning_goals)>0) UNION ALL SELECT u.avatar IS NOT NULL)) AS profileCompletion,(SELECT ROUND(AVG(r.rating),2) FROM reviews r WHERE r.reviewee_id=u.id AND r.review_type='TEACHING') AS teachingAverageRating,(SELECT COUNT(*) FROM reviews r WHERE r.reviewee_id=u.id AND r.review_type='TEACHING') AS teachingReviewCount,(SELECT ROUND(AVG(r.rating),2) FROM reviews r WHERE r.reviewee_id=u.id AND r.review_type='LEARNING') AS learningAverageRating,(SELECT COUNT(*) FROM reviews r WHERE r.reviewee_id=u.id AND r.review_type='LEARNING') AS learningReviewCount,(SELECT MAX(m.created_at) FROM messages m WHERE m.sender_id=u.id) AS lastActivity FROM users u ${where} ORDER BY ${order} LIMIT ? OFFSET ?`).all(...args,limit,offset);
    return send(res,200,{items,pagination:{page,limit,total,pages:Math.ceil(total/limit)}});
  }
  const userRoute=path.match(/^\/api\/admin\/users\/([^/]+)(?:\/(suspend|activate|remove))?$/);
  if(userRoute){let id;try{id=decodeURIComponent(userRoute[1]);}catch{return send(res,404,{error:'User not found.'});}const action=userRoute[2];
    if(method==='GET'&&!action){const user=db.prepare(`SELECT id,name,email,role,CASE WHEN deleted_at IS NOT NULL THEN 'removed' ELSE status END AS status,deleted_at AS deletedAt,verification_status AS verificationStatus,bio,college,location,learning_goals AS learningGoals,profile_visibility AS profileVisibility,created_at AS createdAt,updated_at AS updatedAt,suspended_at AS suspendedAt,suspended_by AS suspendedBy,suspension_reason AS suspensionReason FROM users WHERE id=?`).get(id);if(!user)return send(res,404,{error:'User not found.'});
      const skills=db.prepare(`SELECT us.id,us.type,us.level,s.id AS skillId,s.name,s.category FROM user_skills us JOIN skills s ON s.id=us.skill_id WHERE us.user_id=? ORDER BY us.type,s.name COLLATE NOCASE`).all(id);
      const ratings=db.prepare("SELECT review_type AS reviewType,COUNT(*) AS reviewCount,ROUND(AVG(rating),2) AS averageRating FROM reviews WHERE reviewee_id=? GROUP BY review_type").all(id),teachingRating=ratings.find(x=>x.reviewType==='TEACHING')||{reviewCount:0,averageRating:null},learningRating=ratings.find(x=>x.reviewType==='LEARNING')||{reviewCount:0,averageRating:null};
      const reviews=db.prepare(`SELECT r.id,r.rating,r.comment,r.review_type AS reviewType,r.created_at AS createdAt,u.name AS reviewerName FROM reviews r JOIN users u ON u.id=r.reviewer_id WHERE r.reviewee_id=? ORDER BY r.created_at DESC LIMIT 20`).all(id);
      const swaps=db.prepare(`SELECT sr.id,COALESCE(sr.workflow_status,sr.status) AS status,sender.name AS senderName,receiver.name AS receiverName,offered.name AS skillOffered,wanted.name AS skillWanted,sr.created_at AS createdAt FROM swap_requests sr JOIN users sender ON sender.id=sr.sender_id JOIN users receiver ON receiver.id=sr.receiver_id JOIN skills offered ON offered.id=sr.skill_offered_id JOIN skills wanted ON wanted.id=sr.skill_wanted_id WHERE sr.sender_id=? OR sr.receiver_id=? ORDER BY sr.created_at DESC LIMIT 50`).all(id,id);
      const sessions=db.prepare(`SELECT ss.id,ss.status,ss.start_at AS startAt,ss.end_at AS endAt,ss.timezone,ss.swap_request_id AS swapRequestId FROM skill_sessions ss JOIN swap_requests sr ON sr.id=ss.swap_request_id WHERE sr.sender_id=? OR sr.receiver_id=? ORDER BY ss.start_at DESC LIMIT 50`).all(id,id);
      const payments=db.prepare(`SELECT p.id,p.amount,p.currency,p.status,p.provider,p.session_id AS sessionId,p.created_at AS createdAt FROM payments p WHERE p.user_id=? ORDER BY p.created_at DESC LIMIT 50`).all(id);
      const reports=db.prepare(`SELECT id,reason,status,created_at AS createdAt,reported_user_id AS reportedUserId FROM reports WHERE reporter_id=? OR reported_user_id=? ORDER BY created_at DESC LIMIT 50`).all(id,id);
      const safety={reportCount:Number(db.prepare('SELECT COUNT(*) n FROM reports WHERE reported_user_id=?').get(id).n),blockCount:Number(db.prepare('SELECT COUNT(*) n FROM user_blocks WHERE blocked_user_id=?').get(id).n),moderation:db.prepare(`SELECT action,target_type AS targetType,target_id AS targetId,metadata,created_at AS createdAt FROM admin_audit_logs WHERE target_type='USER' AND target_id=? ORDER BY created_at DESC LIMIT 20`).all(id).map(x=>({...x,metadata:json(x.metadata)}))};
      return send(res,200,{item:{...user,skills,rating:{teaching:teachingRating,learning:learningRating},reviews,swaps,sessions,payments,reports,safety}});
    }
    if(method==='PATCH'&&!action){const target=db.prepare('SELECT id,verification_status AS verificationStatus FROM users WHERE id=?').get(id);if(!target)return send(res,404,{error:'User not found.'});const input=await reqJson(req);const status=String(input.verificationStatus||'').toUpperCase();if(!['VERIFIED','UNVERIFIED'].includes(status))return send(res,400,{error:'Choose a valid verification status.'});if(target.verificationStatus===status)return send(res,409,{error:'Verification status is already set.'});db.prepare('UPDATE users SET verification_status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(status,id);auditAdmin(admin.id,status==='VERIFIED'?'USER_VERIFIED':'USER_UNVERIFIED','USER',id,{});return send(res,200,{ok:true,verificationStatus:status});}
    if(method==='DELETE'&&action==='remove'){
      if(id===admin.id)return send(res,409,{error:'You cannot remove your own administrator account.'});
      const target=db.prepare('SELECT id,role,deleted_at AS deletedAt FROM users WHERE id=?').get(id);
      if(!target)return send(res,404,{error:'User not found.'});
      if(target.role==='admin')return send(res,409,{error:'Administrator accounts cannot be removed here.'});
      if(target.deletedAt)return send(res,409,{error:'This account is already removed.'});
      const now=new Date().toISOString();
      db.exec('BEGIN IMMEDIATE');
      try{
        db.prepare("UPDATE users SET name='Removed user',status='suspended',deleted_at=?,bio='',college='',location='',website='',learning_goals='',avatar=NULL,profile_visibility='PRIVATE',show_email=0,suspension_reason='Account removed',updated_at=? WHERE id=? AND deleted_at IS NULL").run(now,now,id);
        db.prepare('DELETE FROM sessions WHERE user_id=?').run(id);
        auditAdmin(admin.id,'USER_REMOVED','USER',id,{removedAt:now,retainedFinancialAndAuditHistory:true});
        db.exec('COMMIT');
      }catch(error){db.exec('ROLLBACK');throw error;}
      revokeRealtime(id);
      return send(res,200,{ok:true,status:'removed',removedAt:now});
    }
    if(method==='PATCH'&&action==='suspend'){if(id===admin.id)return send(res,409,{error:'You cannot suspend your own administrator account.'});const target=db.prepare('SELECT id,name,role,status,deleted_at AS deletedAt FROM users WHERE id=?').get(id);if(!target)return send(res,404,{error:'User not found.'});if(target.deletedAt)return send(res,409,{error:'This account is removed and cannot be changed.'});if(target.role==='admin')return send(res,409,{error:'Administrator accounts cannot be suspended here.'});if(target.status==='suspended')return send(res,409,{error:'This account is already suspended.'});const input=await reqJson(req);const reason=String(input.reason||'').trim();if(reason.length<5||reason.length>500)return send(res,400,{error:'Enter a suspension reason between 5 and 500 characters.'});const now=new Date().toISOString();db.prepare("UPDATE users SET status='suspended',suspended_at=?,suspended_by=?,suspension_reason=?,updated_at=? WHERE id=? AND status='active'").run(now,admin.id,reason,now,id);auditAdmin(admin.id,'USER_SUSPENDED','USER',id,{reason});adminNotification(id,'Account suspended','Your SkillSwap account has been suspended.','admin-suspended:'+id+':'+now);return send(res,200,{ok:true,status:'suspended',suspendedAt:now});}
    if(method==='PATCH'&&action==='activate'){const target=db.prepare('SELECT id,role,status,deleted_at AS deletedAt FROM users WHERE id=?').get(id);if(!target)return send(res,404,{error:'User not found.'});if(target.deletedAt)return send(res,409,{error:'This account is removed and cannot be reactivated.'});if(target.status==='active')return send(res,409,{error:'This account is already active.'});const now=new Date().toISOString();db.prepare("UPDATE users SET status='active',suspended_at=NULL,suspended_by=NULL,suspension_reason='',updated_at=? WHERE id=? AND status='suspended'").run(now,id);auditAdmin(admin.id,'USER_ACTIVATED','USER',id,{});adminNotification(id,'Account reactivated','Your account has been reactivated.','admin-activated:'+id+':'+now);return send(res,200,{ok:true,status:'active'});}
    return send(res,404,{error:'Not found.'});
  }
  if(path==='/api/admin/skills'&&method==='GET'){
    const {page,limit,offset}=pageArgs(url),q=cleanQuery(url.searchParams.get('q')),category=cleanQuery(url.searchParams.get('category')),active=String(url.searchParams.get('active')||'all').toLowerCase();if(!['all','active','inactive'].includes(active))return send(res,400,{error:'Choose a valid skill status.'});const clauses=[],args=[];if(q){clauses.push('s.name LIKE ?');args.push(`%${q}%`);}if(category){clauses.push('s.category=?');args.push(category);}if(active!=='all'){clauses.push('s.is_active=?');args.push(active==='active'?1:0);}const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:'';const total=Number(db.prepare(`SELECT COUNT(*) AS n FROM skills s ${where}`).get(...args).n);const items=db.prepare(`SELECT s.id,s.name,s.category,s.description,s.is_active AS isActive,s.created_at AS createdAt,(SELECT COUNT(DISTINCT user_id) FROM user_skills WHERE skill_id=s.id) AS userCount FROM skills s ${where} ORDER BY s.name COLLATE NOCASE LIMIT ? OFFSET ?`).all(...args,limit,offset).map(x=>({...x,isActive:!!x.isActive}));const categories=db.prepare('SELECT DISTINCT category FROM skills ORDER BY category COLLATE NOCASE').all().map(x=>x.category);return send(res,200,{items,categories,pagination:{page,limit,total,pages:Math.ceil(total/limit)}});
  }
  if(path==='/api/admin/skills'&&method==='POST'){const input=await reqJson(req);const name=String(input.name||'').trim().replace(/\s+/g,' '),category=String(input.category||'').trim(),description=String(input.description||'').trim();if(name.length<2||name.length>80)return send(res,400,{error:'Skill name must be between 2 and 80 characters.'});if(!categoryValid(category))return send(res,400,{error:'Enter a valid category (up to 50 characters).'});if(description.length>500)return send(res,400,{error:'Skill descriptions are limited to 500 characters.'});if(db.prepare('SELECT 1 FROM skills WHERE name=? COLLATE NOCASE').get(name))return send(res,409,{error:'A skill with this name already exists.'});const id=randomUUID(),isActive=input.status==='inactive'?0:1;db.prepare('INSERT INTO skills(id,owner_id,name,category,description,is_active) VALUES(?,NULL,?,?,?,?)').run(id,name,category,description,isActive);auditAdmin(admin.id,'SKILL_CREATED','SKILL',id,{name,category,status:isActive?'active':'inactive'});return send(res,201,{item:{id,name,category,description,isActive:!!isActive,createdAt:db.prepare('SELECT created_at AS createdAt FROM skills WHERE id=?').get(id).createdAt}});}
  const skillRoute=path.match(/^\/api\/admin\/skills\/([^/]+)(?:\/(activate|deactivate))?$/);if(skillRoute){let id;try{id=decodeURIComponent(skillRoute[1]);}catch{return send(res,404,{error:'Skill not found.'});}const action=skillRoute[2];const target=db.prepare('SELECT id,name,category,description,is_active AS isActive FROM skills WHERE id=?').get(id);if(!target)return send(res,404,{error:'Skill not found.'});if(method==='PATCH'&&action){const active=action==='activate'?1:0;if(Number(target.isActive)===active)return send(res,409,{error:`This skill is already ${active?'active':'inactive'}.`});db.prepare('UPDATE skills SET is_active=? WHERE id=?').run(active,id);auditAdmin(admin.id,active?'SKILL_UPDATED':'SKILL_DEACTIVATED','SKILL',id,{status:active?'active':'inactive'});return send(res,200,{item:{...target,isActive:!!active}});}if(method==='PATCH'&&!action){const input=await reqJson(req),name=String(input.name||'').trim().replace(/\s+/g,' '),category=String(input.category||'').trim(),description=String(input.description||'').trim();if(name.length<2||name.length>80)return send(res,400,{error:'Skill name must be between 2 and 80 characters.'});if(!categoryValid(category)||description.length>500)return send(res,400,{error:'Enter a valid category and a description up to 500 characters.'});if(db.prepare('SELECT 1 FROM skills WHERE id<>? AND name=? COLLATE NOCASE').get(id,name))return send(res,409,{error:'A skill with this name already exists.'});db.prepare('UPDATE skills SET name=?,category=?,description=? WHERE id=?').run(name,category,description,id);auditAdmin(admin.id,'SKILL_UPDATED','SKILL',id,{name,category});return send(res,200,{item:{...target,name,category,description}});}return send(res,404,{error:'Not found.'});}
  if(path==='/api/admin/swaps'&&method==='GET'){const {page,limit,offset}=pageArgs(url),q=cleanQuery(url.searchParams.get('q')),status=String(url.searchParams.get('status')||'ALL').toUpperCase();if(status!=='ALL'&&!statuses.includes(status))return send(res,400,{error:'Choose a valid swap status.'});const clauses=[],args=[];if(status!=='ALL'){clauses.push("COALESCE(sr.workflow_status,sr.status)=?");args.push(status);}if(q){clauses.push('(sr.id LIKE ? OR sender.name LIKE ? OR receiver.name LIKE ? OR offered.name LIKE ? OR wanted.name LIKE ?)');args.push(...Array(5).fill(`%${q}%`));}const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:'';const total=Number(db.prepare(`SELECT COUNT(*) AS n FROM swap_requests sr JOIN users sender ON sender.id=sr.sender_id JOIN users receiver ON receiver.id=sr.receiver_id JOIN skills offered ON offered.id=sr.skill_offered_id JOIN skills wanted ON wanted.id=sr.skill_wanted_id ${where}`).get(...args).n);const items=db.prepare(`SELECT sr.id,sr.sender_id AS senderId,sender.name AS senderName,sender.email AS senderEmail,sr.receiver_id AS receiverId,receiver.name AS receiverName,receiver.email AS receiverEmail,offered.name AS skillOffered,wanted.name AS skillWanted,COALESCE(sr.workflow_status,sr.status) AS status,sr.message,sr.created_at AS createdAt,sr.updated_at AS updatedAt FROM swap_requests sr JOIN users sender ON sender.id=sr.sender_id JOIN users receiver ON receiver.id=sr.receiver_id JOIN skills offered ON offered.id=sr.skill_offered_id JOIN skills wanted ON wanted.id=sr.skill_wanted_id ${where} ORDER BY sr.created_at DESC LIMIT ? OFFSET ?`).all(...args,limit,offset);return send(res,200,{items,pagination:{page,limit,total,pages:Math.ceil(total/limit)}});}
  const swapRoute=path.match(/^\/api\/admin\/swaps\/([^/]+)$/);if(method==='GET'&&swapRoute){let id;try{id=decodeURIComponent(swapRoute[1]);}catch{return send(res,404,{error:'Swap not found.'});}const item=db.prepare(`SELECT sr.id,sr.sender_id AS senderId,sender.name AS senderName,sender.email AS senderEmail,sr.receiver_id AS receiverId,receiver.name AS receiverName,receiver.email AS receiverEmail,offered.id AS skillOfferedId,offered.name AS skillOffered,wanted.id AS skillWantedId,wanted.name AS skillWanted,COALESCE(sr.workflow_status,sr.status) AS status,sr.message,sr.created_at AS createdAt,sr.updated_at AS updatedAt FROM swap_requests sr JOIN users sender ON sender.id=sr.sender_id JOIN users receiver ON receiver.id=sr.receiver_id JOIN skills offered ON offered.id=sr.skill_offered_id JOIN skills wanted ON wanted.id=sr.skill_wanted_id WHERE sr.id=?`).get(id);if(!item)return send(res,404,{error:'Swap not found.'});const sessions=db.prepare('SELECT id,status,start_at AS startAt,end_at AS endAt,timezone,created_at AS createdAt FROM skill_sessions WHERE swap_request_id=? ORDER BY created_at DESC').all(id);const payments=db.prepare('SELECT id,amount,currency,status,provider,created_at AS createdAt FROM payments WHERE swap_request_id=? ORDER BY created_at DESC').all(id);return send(res,200,{item:{...item,sessions,payments}});}
  if(path==='/api/admin/reports'&&method==='GET'){const {page,limit,offset}=pageArgs(url),status=String(url.searchParams.get('status')||'ALL').toUpperCase(),q=cleanQuery(url.searchParams.get('q'));if(status!=='ALL'&&!reportStatuses.includes(status))return send(res,400,{error:'Choose a valid report status.'});const clauses=[],args=[];if(status!=='ALL'){clauses.push('r.status=?');args.push(status);}if(q){clauses.push('(r.reason LIKE ? OR reporter.name LIKE ? OR reported.name LIKE ? OR r.id LIKE ?)');args.push(...Array(4).fill(`%${q}%`));}const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:'';const total=Number(db.prepare(`SELECT COUNT(*) AS n FROM reports r LEFT JOIN users reporter ON reporter.id=r.reporter_id LEFT JOIN users reported ON reported.id=r.reported_user_id ${where}`).get(...args).n);const items=db.prepare(`SELECT r.id,r.reporter_id AS reporterId,reporter.name AS reporterName,r.reported_user_id AS reportedUserId,reported.name AS reportedUserName,r.swap_request_id AS swapRequestId,r.message_id AS messageId,r.reason,r.description,r.status,r.created_at AS createdAt FROM reports r LEFT JOIN users reporter ON reporter.id=r.reporter_id LEFT JOIN users reported ON reported.id=r.reported_user_id ${where} ORDER BY r.created_at DESC LIMIT ? OFFSET ?`).all(...args,limit,offset);return send(res,200,{items,pagination:{page,limit,total,pages:Math.ceil(total/limit)}});}
  const reportRoute=path.match(/^\/api\/admin\/reports\/([^/]+)(?:\/(review|resolve|dismiss))?$/);if(reportRoute){let id;try{id=decodeURIComponent(reportRoute[1]);}catch{return send(res,404,{error:'Report not found.'});}const action=reportRoute[2];if(method==='GET'&&!action){const item=db.prepare(`SELECT r.id,r.reporter_id AS reporterId,reporter.name AS reporterName,reporter.email AS reporterEmail,reporter.bio AS reporterBio,reporter.created_at AS reporterCreatedAt,r.reported_user_id AS reportedUserId,reported.name AS reportedUserName,reported.email AS reportedUserEmail,reported.status AS reportedUserStatus,r.swap_request_id AS swapRequestId,r.message_id AS messageId,r.reason,r.description,r.status,r.admin_note AS adminNote,r.resolved_by AS resolvedBy,resolver.name AS resolvedByName,r.resolved_at AS resolvedAt,r.created_at AS createdAt,r.updated_at AS updatedAt FROM reports r LEFT JOIN users reporter ON reporter.id=r.reporter_id LEFT JOIN users reported ON reported.id=r.reported_user_id LEFT JOIN users resolver ON resolver.id=r.resolved_by WHERE r.id=?`).get(id);if(!item)return send(res,404,{error:'Report not found.'});let swap=null,message=null,sessions=[];if(item.swapRequestId){swap=db.prepare(`SELECT sr.id,COALESCE(sr.workflow_status,sr.status) AS status,sender.name AS senderName,receiver.name AS receiverName,offered.name AS skillOffered,wanted.name AS skillWanted,sr.message,sr.created_at AS createdAt FROM swap_requests sr JOIN users sender ON sender.id=sr.sender_id JOIN users receiver ON receiver.id=sr.receiver_id JOIN skills offered ON offered.id=sr.skill_offered_id JOIN skills wanted ON wanted.id=sr.skill_wanted_id WHERE sr.id=?`).get(item.swapRequestId);sessions=db.prepare('SELECT id,status,start_at AS startAt,end_at AS endAt,timezone FROM skill_sessions WHERE swap_request_id=?').all(item.swapRequestId);}if(item.messageId)message=db.prepare(`SELECT m.id,m.content,m.created_at AS createdAt,sender.name AS senderName,peer.name AS otherParticipantName FROM messages m JOIN users sender ON sender.id=m.sender_id JOIN conversations c ON c.id=m.conversation_id JOIN users peer ON peer.id=CASE WHEN c.user_one_id=m.sender_id THEN c.user_two_id ELSE c.user_one_id END WHERE m.id=?`).get(item.messageId);return send(res,200,{item:{...item,swap,message,sessions}});}
    if(method==='PATCH'&&['review','resolve','dismiss'].includes(action)){const report=db.prepare('SELECT id,status,reporter_id AS reporterId FROM reports WHERE id=?').get(id);if(!report)return send(res,404,{error:'Report not found.'});const input=await reqJson(req),note=String(input.adminNote||'').trim();if(note.length>1000)return send(res,400,{error:'Admin notes are limited to 1000 characters.'});if(action==='review'&&report.status!=='OPEN')return send(res,409,{error:'Only open reports can be moved under review.'});if(action==='resolve'&& !['OPEN','UNDER_REVIEW'].includes(report.status))return send(res,409,{error:'This report is already closed.'});if(action==='dismiss'&&!['OPEN','UNDER_REVIEW'].includes(report.status))return send(res,409,{error:'This report is already closed.'});const status=action==='review'?'UNDER_REVIEW':action==='resolve'?'RESOLVED':'DISMISSED',now=new Date().toISOString();db.prepare('UPDATE reports SET status=?,admin_note=?,resolved_by=?,resolved_at=?,updated_at=? WHERE id=?').run(status,note,admin.id,action==='review'?null:now,now,id);const auditAction=action==='review'?'REPORT_REVIEWED':action==='resolve'?'REPORT_RESOLVED':'REPORT_DISMISSED';auditAdmin(admin.id,auditAction,'REPORT',id,{status,adminNote:note});if(report.reporterId)adminNotification(report.reporterId,'Report reviewed','Your report has been reviewed.','report-review:'+id+':'+status);return send(res,200,{ok:true,status});}
    return send(res,404,{error:'Not found.'});
  }
  if(path==='/api/admin/payments'&&method==='GET'){const {page,limit,offset}=pageArgs(url),q=cleanQuery(url.searchParams.get('q')),status=String(url.searchParams.get('status')||'ALL').toUpperCase(),valid=['ALL','SUCCESS','PENDING','CREATED','FAILED','CANCELLED','REFUNDED'];if(!valid.includes(status))return send(res,400,{error:'Choose a valid payment status.'});const clauses=[],args=[];if(status==='PENDING')clauses.push("p.status IN ('PENDING','CREATED')");else if(status!=='ALL'){clauses.push('p.status=?');args.push(status);}if(q){clauses.push('(u.name LIKE ? OR u.email LIKE ? OR p.id LIKE ? OR p.provider_payment_id LIKE ?)');args.push(...Array(4).fill(`%${q}%`));}const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:'';const total=Number(db.prepare(`SELECT COUNT(*) AS n FROM payments p JOIN users u ON u.id=p.user_id ${where}`).get(...args).n);const items=db.prepare(`SELECT p.id,p.user_id AS userId,u.name AS userName,u.email AS userEmail,p.amount,p.currency,p.status,p.provider,p.provider_payment_id AS providerPaymentId,p.session_id AS sessionId,ss.start_at AS sessionStartAt,p.created_at AS createdAt FROM payments p JOIN users u ON u.id=p.user_id LEFT JOIN skill_sessions ss ON ss.id=p.session_id ${where} ORDER BY p.created_at DESC LIMIT ? OFFSET ?`).all(...args,limit,offset);return send(res,200,{items,pagination:{page,limit,total,pages:Math.ceil(total/limit)}});}
  if(path==='/api/admin/subscriptions'&&method==='GET'){const {page,limit}=pageArgs(url),status=String(url.searchParams.get('status')||'ALL').toUpperCase(),q=cleanQuery(url.searchParams.get('q'));if(!['ALL','ACTIVE','PENDING','EXPIRED','CANCELLED'].includes(status))return send(res,400,{error:'Choose a valid subscription status.'});return send(res,200,subscriptionService.adminList({page,limit,status,q}));}
  if(path==='/api/admin/audit-logs'&&method==='GET'){const {page,limit,offset}=pageArgs(url),action=cleanQuery(url.searchParams.get('action')),targetType=cleanQuery(url.searchParams.get('targetType')).toUpperCase(),adminId=cleanQuery(url.searchParams.get('adminId')),from=cleanQuery(url.searchParams.get('from')),to=cleanQuery(url.searchParams.get('to'));const clauses=[],args=[];if(action){clauses.push('l.action=?');args.push(action);}if(targetType){clauses.push('l.target_type=?');args.push(targetType);}if(adminId){clauses.push('l.admin_id=?');args.push(adminId);}if(from&&/^\d{4}-\d{2}-\d{2}$/.test(from)){clauses.push("l.created_at>=datetime(?,'start of day')");args.push(from);}if(to&&/^\d{4}-\d{2}-\d{2}$/.test(to)){clauses.push("l.created_at<datetime(?,'+1 day')");args.push(to);}const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:'';const total=Number(db.prepare(`SELECT COUNT(*) AS n FROM admin_audit_logs l ${where}`).get(...args).n);const items=db.prepare(`SELECT l.id,l.admin_id AS adminId,u.name AS adminName,l.action,l.target_type AS targetType,l.target_id AS targetId,l.metadata,l.created_at AS createdAt FROM admin_audit_logs l LEFT JOIN users u ON u.id=l.admin_id ${where} ORDER BY l.created_at DESC LIMIT ? OFFSET ?`).all(...args,limit,offset).map(x=>({...x,metadata:json(x.metadata)}));const admins=db.prepare("SELECT id,name FROM users WHERE role='admin' ORDER BY name COLLATE NOCASE").all();return send(res,200,{items,admins,pagination:{page,limit,total,pages:Math.ceil(total/limit)}});}
  if(method==='GET'&&path==='/api/admin/settings')return send(res,200,{platform:{name:process.env.PLATFORM_NAME||'SkillSwap',supportEmail:process.env.SUPPORT_EMAIL||'',defaultCurrency:(process.env.PAYMENT_CURRENCY||'INR').toUpperCase(),maintenanceMode:false},administrator:{name:admin.name,email:admin.email}});
  return send(res,404,{error:'Not found.'});
}

async function reqJson(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>16384)throw Object.assign(new Error('Request body too large.'),{status:413});}try{return raw?JSON.parse(raw):{};}catch{throw Object.assign(new Error('Invalid JSON.'),{status:400});}}

export async function createUserReport({req,res,url,db,user,send,randomUUID,adminNotification}){
  if(req.method!=='POST')return send(res,405,{error:'Method not allowed.'});
  const recent=Number(db.prepare("SELECT COUNT(*) AS n FROM reports WHERE reporter_id=? AND created_at>=datetime('now','-1 hour')").get(user.id).n);if(recent>=5)return send(res,429,{error:'You have sent several reports recently. Please try again later.'});
  const input=await reqJson(req),targetType=String(input.targetType||'').toUpperCase(),targetId=String(input.targetId||''),reason=String(input.reason||'').trim(),description=String(input.description||'').trim();
  if(!['USER','SWAP','MESSAGE'].includes(targetType)||!targetId||targetId.length>100)return send(res,400,{error:'Choose a valid report target.'});
  if(!reportReasons.includes(reason))return send(res,400,{error:'Choose a valid report reason.'});if(description.length<10||description.length>2000)return send(res,400,{error:'Description must be between 10 and 2000 characters.'});
  let reportedUserId=null,swapRequestId=null,messageId=null;
  if(targetType==='USER'){reportedUserId=targetId;if(reportedUserId===user.id)return send(res,400,{error:'You cannot report your own account.'});if(!db.prepare('SELECT id FROM users WHERE id=?').get(reportedUserId))return send(res,404,{error:'Reported user not found.'});}
  if(targetType==='SWAP'){const swap=db.prepare('SELECT id,sender_id AS senderId,receiver_id AS receiverId FROM swap_requests WHERE id=?').get(targetId);if(!swap)return send(res,404,{error:'Swap request not found.'});if(user.id!==swap.senderId&&user.id!==swap.receiverId)return send(res,403,{error:'Only exchange participants can report this swap.'});reportedUserId=user.id===swap.senderId?swap.receiverId:swap.senderId;swapRequestId=swap.id;}
  if(targetType==='MESSAGE'){const message=db.prepare('SELECT m.id,m.sender_id AS senderId,c.user_one_id AS userOneId,c.user_two_id AS userTwoId FROM messages m JOIN conversations c ON c.id=m.conversation_id WHERE m.id=? AND m.is_system=0').get(targetId);if(!message)return send(res,404,{error:'Message not found.'});if(user.id!==message.userOneId&&user.id!==message.userTwoId)return send(res,403,{error:'Only conversation participants can report this message.'});if(user.id===message.senderId)return send(res,400,{error:'You cannot report your own message.'});reportedUserId=message.senderId;messageId=message.id;}
  if(db.prepare("SELECT 1 FROM reports WHERE reporter_id=? AND reported_user_id=? AND status IN ('OPEN','UNDER_REVIEW') AND created_at>=datetime('now','-24 hours') AND COALESCE(swap_request_id,'')=? AND COALESCE(message_id,'')=? LIMIT 1").get(user.id,reportedUserId,swapRequestId||'',messageId||''))return send(res,409,{error:'You already submitted a report about this item recently.'});
  const id=randomUUID();db.prepare("INSERT INTO reports(id,status,reporter_id,reported_user_id,swap_request_id,message_id,reason,description) VALUES(?,'OPEN',?,?,?,?,?,?)").run(id,user.id,reportedUserId,swapRequestId,messageId,reason,description);for(const moderator of db.prepare("SELECT id FROM users WHERE role='admin' AND status='active'").all())adminNotification(moderator.id,'New moderation report','A SkillSwap member submitted a report for review.',`report-created:${id}:${moderator.id}`);return send(res,201,{item:{id,status:'OPEN',reason,description,reportedUserId,swapRequestId,messageId}});
}
