import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve,join } from 'node:path';
import { randomUUID,randomBytes,scryptSync } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';

test('admin moderation, role protection, reports, audit, and suspended-user restrictions', {timeout:60000}, async t=>{
  const root=resolve(import.meta.dirname,'..'),dir=mkdtempSync(join(tmpdir(),'skillswap-admin-')),dbPath=join(dir,'admin.sqlite'),port=32000+Math.floor(Math.random()*15000),secret=randomBytes(32).toString('hex');
  const server=spawn(process.execPath,['backend/server.mjs'],{cwd:root,env:{...process.env,API_PORT:String(port),SKILLSWAP_DB_PATH:dbPath,SESSION_SECRET:secret,RECOMMENDATION_MATCH_WEIGHT:'0.65',RECOMMENDATION_DIRECT_BONUS:'20',RECOMMENDATION_MUTUAL_BONUS:'15',RECOMMENDATION_OTHER_BONUS:'10',RECOMMENDATION_RATING_BONUS:'5',RECOMMENDATION_AVAILABILITY_BONUS:'5'},stdio:['ignore','pipe','pipe']});let serverOutput='';server.stdout.on('data',x=>serverOutput+=x);server.stderr.on('data',x=>serverOutput+=x);const streamControllers=[];
  t.after(()=>{for(const controller of streamControllers)controller.abort();server.kill();try{rmSync(dir,{recursive:true,force:true})}catch{}});
  const base=`http://127.0.0.1:${port}`;let ready=false;for(let i=0;i<80;i++){if(server.exitCode!==null)break;try{const r=await fetch(base+'/api/health');if(r.ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,150));}assert.equal(ready,true,`API did not start: ${serverOutput}`);
  const database=new DatabaseSync(dbPath),adminId=randomUUID(),adminEmail='admin@skillswap.test',adminPassword='Test-Admin-Pass-123';const salt=randomBytes(16);database.prepare("INSERT INTO users(id,name,email,password_hash,role,status) VALUES(?,?,?,?,'admin','active')").run(adminId,'Moderator',adminEmail,`scrypt:${salt.toString('hex')}:${scryptSync(adminPassword,salt,64).toString('hex')}`);
  const call=async(path,{method='GET',cookie,body,rawBody,origin}={})=>{const headers={};if(cookie)headers.cookie=cookie;if(body!==undefined||rawBody!==undefined)headers['content-type']='application/json';if(origin)headers.origin=origin;const response=await fetch(base+path,{method,headers,body:rawBody??(body===undefined?undefined:JSON.stringify(body))});const data=await response.json().catch(()=>({}));return{status:response.status,data,cookie:response.headers.get('set-cookie')?.split(';')[0],allowOrigin:response.headers.get('access-control-allow-origin')}};
  const anon=await call('/api/admin/dashboard');assert.equal(anon.status,401);
  assert.equal((await call('/api/realtime/events')).status,401);
  assert.equal((await call('/api/auth/register',{method:'POST',body:{name:'',email:'not-an-email',password:'weak'}})).status,400);
  assert.equal((await call('/api/auth/login',{method:'POST',rawBody:'{'})).status,400);
  const crossOrigin=await call('/api/auth/logout',{method:'POST',origin:'https://untrusted.invalid'});assert.equal(crossOrigin.status,403);assert.equal(crossOrigin.allowOrigin,null);
  assert.equal((await call('/api/recommendations/users')).status,401);
  assert.equal((await call('/api/blocks',{method:'GET'})).status,401);assert.equal((await call('/api/account/export',{method:'POST'})).status,401);assert.equal((await call('/api/settings/privacy',{method:'GET'})).status,401);
  for(let i=0;i<10;i++)assert.equal((await call('/api/auth/login',{method:'POST',body:{email:'unknown@skillswap.test',password:'wrong'}})).status,401);
  assert.equal((await call('/api/auth/login',{method:'POST',body:{email:'unknown@skillswap.test',password:'wrong'}})).status,429);
  const unknownReset=await call('/api/auth/password-reset',{method:'POST',body:{email:'unknown@skillswap.test'}});assert.equal(unknownReset.status,503);assert.equal(unknownReset.data.error,'Password reset is not configured. Please contact support.');
  const registered=await call('/api/auth/register',{method:'POST',body:{name:'Member One',email:'one@skillswap.test',password:'Member-Pass-12345'}});assert.equal(registered.status,201);const userCookie=registered.cookie,userId=registered.data.user.id;
  const noSubscription=await call('/api/subscriptions/current',{cookie:userCookie});assert.equal(noSubscription.status,200);assert.equal(noSubscription.data.active,false);
  const subscriptionCatalog=await call('/api/subscriptions',{cookie:userCookie});assert.equal(subscriptionCatalog.status,200);assert.deepEqual(subscriptionCatalog.data.plans.map(plan=>[plan.plan,plan.amount,plan.days]),[['WEEKLY',2000,7],['MONTHLY',8000,30]]);
  assert.equal((await call('/api/auth/register',{method:'POST',body:{name:'Member One',email:'one@skillswap.test',password:'Another-Pass-12345'}})).status,409);
  const knownReset=await call('/api/auth/password-reset',{method:'POST',body:{email:'one@skillswap.test'}});assert.equal(knownReset.status,503);assert.equal(knownReset.data.error,unknownReset.data.error);assert.notEqual(knownReset.data.requestId,unknownReset.data.requestId);
  assert.equal(JSON.stringify(registered.data).includes('password_hash'),false);assert.equal(JSON.stringify(registered.data).includes('Member-Pass-12345'),false);
  const second=await call('/api/auth/register',{method:'POST',body:{name:'Member Two',email:'two@skillswap.test',password:'Member-Pass-12345'}});assert.equal(second.status,201);const otherId=second.data.user.id;
  const badRole=await call('/api/admin/dashboard',{cookie:userCookie});assert.equal(badRole.status,403);
  const logged=await call('/api/admin/auth/login',{method:'POST',body:{email:adminEmail,password:adminPassword}});assert.equal(logged.status,200);const adminCookie=logged.cookie;
  assert.equal((await call('/api/recommendations/users',{cookie:adminCookie})).status,403);
  const dashboard=await call('/api/admin/dashboard',{cookie:adminCookie});assert.equal(dashboard.status,200);assert.equal(dashboard.data.stats.totalUsers,3);assert.equal(dashboard.data.stats.activeUsers,3);
  assert.equal(dashboard.data.stats.aiRecommendationRequests,0);assert.equal(JSON.stringify(dashboard.data).includes('AI_API_KEY'),false);
  const users=await call('/api/admin/users?q=Member&page=1&limit=1',{cookie:adminCookie});assert.equal(users.status,200);assert.equal(users.data.pagination.total,2);assert.equal(users.data.items.length,1);
  const detail=await call(`/api/admin/users/${userId}`,{cookie:adminCookie});assert.equal(detail.status,200);assert.ok('rating' in detail.data.item);
  assert.equal((await call(`/api/admin/users/${userId}`,{method:'PATCH',cookie:userCookie,body:{verificationStatus:'VERIFIED'}})).status,403);
  assert.equal((await call(`/api/admin/users/${userId}`,{method:'PATCH',cookie:adminCookie,body:{verificationStatus:'VERIFIED'}})).data.verificationStatus,'VERIFIED');
  assert.equal((await call(`/api/admin/users/${userId}`,{cookie:adminCookie})).data.item.verificationStatus,'VERIFIED');
  const suspended=await call(`/api/admin/users/${userId}/suspend`,{method:'PATCH',cookie:adminCookie,body:{reason:'Repeated abusive contact'}});assert.equal(suspended.status,200);
  const denied=await call('/api/availability/me',{cookie:userCookie});assert.equal(denied.status,403);assert.match(denied.data.error,/currently suspended/);
  const loginDenied=await call('/api/auth/login',{method:'POST',body:{email:'one@skillswap.test',password:'Member-Pass-12345'}});assert.equal(loginDenied.status,403);
  assert.equal((await call(`/api/admin/users/${userId}/activate`,{method:'PATCH',cookie:adminCookie})).status,200);assert.equal((await call('/api/availability/me',{cookie:userCookie})).status,200);
  const createdSkill=await call('/api/admin/skills',{method:'POST',cookie:adminCookie,body:{name:'  Pottery   Basics ',category:'Arts',description:'Hands-on pottery.'}});assert.equal(createdSkill.status,201);const skillId=createdSkill.data.item.id;assert.equal(createdSkill.data.item.name,'Pottery Basics');assert.equal((await call('/api/admin/skills',{method:'POST',cookie:adminCookie,body:{name:'pottery basics',category:'Arts'}})).status,409);
  assert.equal((await call(`/api/admin/skills/${skillId}/deactivate`,{method:'PATCH',cookie:adminCookie})).status,200);assert.equal((await call(`/api/admin/skills?active=inactive`,{cookie:adminCookie})).data.items.some(x=>x.id===skillId),true);
  assert.equal((await call('/api/skills',{cookie:userCookie})).data.items.some(x=>x.id===skillId),false);
  const activeSkill=await call('/api/admin/skills',{method:'POST',cookie:adminCookie,body:{name:'Woodworking',category:'Crafts'}});assert.equal(activeSkill.status,201);const skill2=activeSkill.data.item.id;
  const teachSkill=await call('/api/skills/user',{method:'POST',cookie:userCookie,body:{skillId:skill2,type:'TEACH',level:'INTERMEDIATE'}});assert.equal(teachSkill.status,201);assert.equal(teachSkill.data.item.type,'TEACH');
  const learnSkill=await call('/api/skills/user',{method:'POST',cookie:userCookie,body:{skillId:skill2,type:'LEARN',level:'BEGINNER'}});assert.equal(learnSkill.status,201);assert.equal(learnSkill.data.item.type,'LEARN');
  assert.equal((await call('/api/skills/user',{method:'POST',cookie:userCookie,body:{skillId:skill2,type:'TEACH',level:'EXPERT'}})).status,409);
  assert.equal((await call(`/api/skills/user/${teachSkill.data.item.id}`,{method:'DELETE',cookie:second.cookie})).status,404);
  assert.equal((await call('/api/skills/user',{method:'POST',cookie:userCookie,body:{skillId:'invalid-skill-id',type:'TEACH',level:'BEGINNER'}})).status,400);
  const pairs=[];for(let i=0;i<11;i++){const offered=randomUUID(),wanted=randomUUID();database.prepare('INSERT INTO skills(id,owner_id,name,category,description,is_active) VALUES(?,NULL,?,?,\'\',1)').run(offered,`Offer ${i}`,'Test');database.prepare('INSERT INTO skills(id,owner_id,name,category,description,is_active) VALUES(?,NULL,?,?,\'\',1)').run(wanted,`Wanted ${i}`,'Test');database.prepare('INSERT INTO user_skills(id,user_id,skill_id,type,level) VALUES(?,?,?,\'TEACH\',\'INTERMEDIATE\')').run(randomUUID(),userId,offered);database.prepare('INSERT INTO user_skills(id,user_id,skill_id,type,level) VALUES(?,?,?,\'LEARN\',\'BEGINNER\')').run(randomUUID(),userId,wanted);database.prepare('INSERT INTO user_skills(id,user_id,skill_id,type,level) VALUES(?,?,?,\'TEACH\',\'EXPERT\')').run(randomUUID(),otherId,wanted);pairs.push({offered,wanted});}
  const javaScriptId=database.prepare("SELECT id FROM skills WHERE name='JavaScript'").get().id;database.prepare("INSERT INTO user_skills(id,user_id,skill_id,type,level) VALUES(?,?,?,'TEACH','ADVANCED')").run(randomUUID(),otherId,javaScriptId);database.prepare("UPDATE users SET learning_goals='I want to learn JavaScript and React' WHERE id=?").run(userId);
  const discoveryRatings=await call('/api/discovery?type=people&q=JavaScript',{cookie:userCookie});assert.equal(discoveryRatings.status,200);assert.ok(discoveryRatings.data.people.results.some(x=>x.user.id===otherId));assert.ok('teachingRating' in discoveryRatings.data.people.results[0].user);assert.ok('learningRating' in discoveryRatings.data.people.results[0].user);
  const overlapDay=new Date(Date.now()+86400000).getUTCDay();for(const id of [userId,otherId])database.prepare("INSERT INTO availability_slots(id,user_id,day_of_week,start_time,end_time,timezone,is_active) VALUES(?,?,?,'10:00','12:00','UTC',1)").run(randomUUID(),id,overlapDay);
  const recUsers=await call('/api/recommendations/users',{cookie:userCookie});assert.equal(recUsers.status,200);assert.ok(recUsers.data.items.some(x=>x.user.id===otherId));assert.ok(recUsers.data.items[0].reason);assert.ok(recUsers.data.items[0].matchScore>0);assert.ok(recUsers.data.items[0].recommendationScore>0);assert.equal(recUsers.data.items.find(x=>x.user.id===otherId).availabilityCompatibility,true);assert.ok(recUsers.data.items.find(x=>x.user.id===otherId).reasons.includes('Your listed weekly availability overlaps.'));
  assert.equal((await call('/api/recommendations/users',{cookie:userCookie})).status,200);assert.ok(database.prepare("SELECT COUNT(*) n FROM recommendation_health WHERE event='cache'").get().n>0);
  const recSkills=await call('/api/recommendations/skills',{cookie:userCookie});assert.equal(recSkills.status,200);assert.ok(recSkills.data.items.some(x=>x.skillId===javaScriptId&&x.reason.includes('JavaScript')));
  const learningPath=await call('/api/recommendations/learning-path',{cookie:userCookie});assert.equal(learningPath.status,200);assert.ok(learningPath.data.items.some(x=>x.skillId===javaScriptId));
  assert.equal((await call('/api/recommendations/feedback',{method:'POST',cookie:userCookie,body:{targetType:'USER',targetId:otherId,feedback:'NOT_INTERESTED'}})).status,200);assert.equal((await call('/api/recommendations/users',{cookie:userCookie})).data.items.some(x=>x.user.id===otherId),false);
  assert.equal((await call('/api/recommendations/feedback',{method:'POST',cookie:userCookie,body:{targetType:'USER',targetId:otherId,feedback:'INTERESTED'}})).status,200);assert.equal(database.prepare('SELECT COUNT(*) n FROM recommendation_feedback WHERE user_id=? AND target_type=\'USER\' AND target_id=?').get(userId,otherId).n,1);assert.equal((await call('/api/recommendations/users',{cookie:userCookie})).data.items.some(x=>x.user.id===otherId),true);
  assert.equal((await call('/api/recommendations/feedback',{method:'POST',cookie:userCookie,body:{targetType:'SKILL',targetId:javaScriptId,feedback:'NOT_INTERESTED'}})).status,200);assert.equal((await call('/api/recommendations/skills',{cookie:userCookie})).data.items.some(x=>x.skillId===javaScriptId),false);
  assert.equal((await call('/api/recommendations/feedback',{method:'POST',cookie:userCookie,body:{targetType:'SKILL',targetId:javaScriptId,feedback:'INTERESTED'}})).status,200);assert.equal(database.prepare('SELECT COUNT(*) n FROM recommendation_feedback WHERE user_id=? AND target_type=\'SKILL\' AND target_id=?').get(userId,javaScriptId).n,1);
  database.prepare("UPDATE users SET profile_visibility='PRIVATE' WHERE id=?").run(otherId);assert.equal((await call('/api/recommendations/users',{cookie:userCookie})).data.items.some(x=>x.user.id===otherId),false);database.prepare("UPDATE users SET profile_visibility='PUBLIC' WHERE id=?").run(otherId);
  for(let i=0;i<10;i++){const sent=await call('/api/swap-requests',{method:'POST',cookie:userCookie,body:{receiverId:otherId,skillOfferedId:pairs[i].offered,skillWantedId:pairs[i].wanted,message:'A reasonable exchange request.'}});assert.equal(sent.status,201);database.prepare("UPDATE swap_requests SET workflow_status='CANCELLED',status='CANCELLED' WHERE id=?").run(sent.data.item.id);}
  assert.equal((await call('/api/swap-requests',{method:'POST',cookie:userCookie,body:{receiverId:otherId,skillOfferedId:pairs[10].offered,skillWantedId:pairs[10].wanted,message:'Another reasonable request.'}})).status,429);
  const swapId=randomUUID(),now=new Date().toISOString();database.prepare("INSERT INTO swap_requests(id,sender_id,receiver_id,skill_offered_id,skill_wanted_id,message,workflow_status,created_at,updated_at) VALUES(?,?,?,?,?,?,'PENDING',?,?)").run(swapId,userId,otherId,skillId,skill2,'Exchange please',now,now);
  const completedSwapId=randomUUID();database.prepare("INSERT INTO swap_requests(id,sender_id,receiver_id,skill_offered_id,skill_wanted_id,message,status,workflow_status,completed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,'ACCEPTED','COMPLETED',?,?,?)").run(completedSwapId,userId,otherId,pairs[0].offered,pairs[0].wanted,'Completed exchange',now,now,now);
  const activeSwapId=randomUUID();database.prepare("INSERT INTO swap_requests(id,sender_id,receiver_id,skill_offered_id,skill_wanted_id,message,status,workflow_status,accepted_at,created_at,updated_at) VALUES(?,?,?,?,?,?,'ACCEPTED','ACCEPTED',?,?,?)").run(activeSwapId,userId,otherId,pairs[1].offered,pairs[1].wanted,'Active exchange',now,now,now);
  const reviewBody={revieweeId:otherId,swapRequestId:completedSwapId,rating:5,comment:'A thoughtful and helpful lesson.',reviewType:'TEACHING'};assert.equal((await call('/api/reviews',{method:'POST',cookie:userCookie,body:reviewBody})).status,201);assert.equal((await call('/api/reviews',{method:'POST',cookie:userCookie,body:reviewBody})).status,409);
  assert.equal((await call('/api/reviews',{method:'POST',cookie:userCookie,body:{...reviewBody,rating:4,reviewType:'LEARNING'}})).status,201);
  const separateRatings=await call(`/api/reviews/user/${otherId}/summary`);assert.equal(separateRatings.status,200);assert.equal(separateRatings.data.teachingAverageRating,5);assert.equal(separateRatings.data.teachingReviewCount,1);assert.equal(separateRatings.data.learningAverageRating,4);assert.equal(separateRatings.data.learningReviewCount,1);
  assert.equal((await call(`/api/reviews/user/${otherId}?type=LEARNING`,{cookie:userCookie})).data.items[0].reviewType,'LEARNING');
  const conversationId=randomUUID(),[one,two]=[userId,otherId].sort();database.prepare('INSERT INTO conversations(id,user_one_id,user_two_id) VALUES(?,?,?)').run(conversationId,one,two);database.prepare('INSERT INTO conversation_participants(conversation_id,user_id) VALUES(?,?),(?,?)').run(conversationId,one,conversationId,two);
  assert.equal((await call(`/api/conversations/${conversationId}/messages`,{method:'POST',cookie:userCookie,body:{content:'   '}})).status,400);
  assert.equal((await call(`/api/conversations/${conversationId}/messages`,{method:'POST',cookie:userCookie,body:{content:'x'.repeat(2001)}})).status,400);
  for(let i=0;i<30;i++)assert.equal((await call(`/api/conversations/${conversationId}/messages`,{method:'POST',cookie:userCookie,body:{content:`Normal message ${i}`}})).status,201);
  assert.equal((await call(`/api/conversations/${conversationId}/messages`,{method:'POST',cookie:userCookie,body:{content:'Too many messages'}})).status,429);
  const messageId=randomUUID();database.prepare('INSERT INTO messages(id,conversation_id,sender_id,content) VALUES(?,?,?,?)').run(messageId,conversationId,otherId,'Please send an inappropriate payment.');
  const outsiderRegistration=await call('/api/auth/register',{method:'POST',body:{name:'Outsider',email:'outsider@skillswap.test',password:'Member-Pass-12345'}});assert.equal(outsiderRegistration.status,201);const outsiderCookie=outsiderRegistration.cookie;
  assert.equal((await call(`/api/conversations/${conversationId}/messages`,{cookie:outsiderCookie})).status,404);
  assert.equal((await call(`/api/conversations/${conversationId}/read`,{method:'PATCH',cookie:userCookie})).status,200);assert.ok(database.prepare('SELECT COUNT(*) AS n FROM messages WHERE conversation_id=? AND sender_id!=? AND read_at IS NOT NULL').get(conversationId,userId).n>0);
  assert.equal((await call(`/api/blocks/${userId}`,{method:'POST',cookie:second.cookie})).status,201);
  assert.equal((await call(`/api/blocks/${userId}`,{method:'POST',cookie:second.cookie})).status,409);
  const discovery=await call('/api/discovery?type=people&q=Member%20Two',{cookie:userCookie});assert.equal(discovery.status,200);assert.equal(discovery.data.people.results.some(x=>x.user.id===otherId),false);
  assert.equal((await call('/api/recommendations/users',{cookie:userCookie})).data.items.some(x=>x.user.id===otherId),false);
  assert.equal((await call(`/api/conversations/${conversationId}/messages`,{method:'POST',cookie:userCookie,body:{content:'A message while blocked'}})).status,403);
  assert.equal((await call('/api/sessions',{method:'POST',cookie:userCookie,body:{swapRequestId:activeSwapId}})).status,403);
  assert.equal((await call('/api/swap-requests',{method:'POST',cookie:second.cookie,body:{receiverId:userId,skillOfferedId:skill2,skillWantedId:skillId}})).status,403);
  assert.equal((await call(`/api/blocks/${userId}`,{method:'DELETE',cookie:second.cookie})).status,200);
  assert.equal((await call('/api/blocks',{cookie:second.cookie})).data.items.length,0);
  const userNotifications=await call('/api/notifications',{cookie:userCookie});assert.equal(userNotifications.status,200);assert.ok(userNotifications.data.items.length>0);const notificationId=userNotifications.data.items[0].id;
  assert.equal((await call(`/api/notifications/${notificationId}/read`,{method:'PATCH',cookie:userCookie})).status,200);
  assert.equal((await call('/api/notifications/read-all',{method:'PATCH',cookie:userCookie})).status,200);
  assert.equal((await call('/api/notifications/read',{method:'DELETE',cookie:userCookie})).status,200);
  assert.equal((await call('/api/reviews',{method:'POST',cookie:userCookie,body:{revieweeId:otherId,swapRequestId:swapId,rating:5,comment:'Not completed'}})).status,403);
  const privacy=await call('/api/settings/privacy',{cookie:userCookie});assert.equal(privacy.status,200);assert.equal(privacy.data.settings.allowDirectMessages,true);
  assert.equal((await call('/api/settings/privacy',{method:'PATCH',cookie:userCookie,body:{...privacy.data.settings,showEmail:false,showAvailability:false,showReviews:false}})).status,200);
  const privateAvailability=await call('/api/recommendations/users',{cookie:userCookie});assert.equal(privateAvailability.data.items.some(x=>x.reasons.includes('Your listed weekly availability overlaps.')),false);assert.equal(privateAvailability.data.items.find(x=>x.user.id===otherId)?.availabilityCompatibility,null);
  assert.equal((await call(`/api/profile/${userId}`,{cookie:second.cookie})).data.profile.showReviews,false);
  const exported=await call('/api/account/export',{method:'POST',cookie:userCookie});assert.equal(exported.status,200);assert.equal(JSON.stringify(exported.data).includes('password_hash'),false);assert.equal(JSON.stringify(exported.data).includes(secret),false);
  const avatarUpload=await fetch(base+'/api/profile/avatar',{method:'POST',headers:{cookie:userCookie,'content-type':'image/png'},body:Buffer.from('not-an-image')});assert.equal(avatarUpload.status,400);
  const oversizedBody=await fetch(base+'/api/account/export',{method:'POST',headers:{cookie:userCookie,'content-type':'application/json'},body:JSON.stringify({oversized:'x'.repeat(20*1024)})});assert.equal(oversizedBody.status,413);
  database.prepare("UPDATE users SET status='suspended' WHERE id=?").run(otherId);assert.equal((await call('/api/recommendations/users',{cookie:userCookie})).data.items.some(x=>x.user.id===otherId),false);database.prepare("UPDATE users SET status='active' WHERE id=?").run(otherId);
  let recommendationLimited=false;for(let i=0;i<35;i++){const response=await call('/api/recommendations/users',{cookie:userCookie});if(response.status===429){assert.match(response.data.error,/temporarily unavailable/i);recommendationLimited=true;break;}assert.equal(response.status,200);}assert.equal(recommendationLimited,true);
  const monitored=await call('/api/admin/dashboard',{cookie:adminCookie});assert.equal(monitored.status,200);assert.equal(monitored.data.stats.aiRecommendationRequests,0);assert.ok(monitored.data.stats.recommendationFallbacks>0);assert.ok(monitored.data.stats.recommendationCacheHits>0);
  const otherLogin=await call('/api/auth/login',{method:'POST',body:{email:'one@skillswap.test',password:'Member-Pass-12345'}});assert.equal(otherLogin.status,200);
  assert.equal((await call('/api/account/logout-all',{method:'POST',cookie:userCookie})).status,200);assert.equal((await call('/api/auth/session',{cookie:otherLogin.cookie})).status,401);assert.equal((await call('/api/auth/session',{cookie:userCookie})).status,200);
  assert.equal((await call('/api/account/password',{method:'POST',cookie:userCookie,body:{currentPassword:'Member-Pass-12345',newPassword:'Updated-Member-Pass-123'}})).status,200);
  const savedPassword=database.prepare('SELECT password_hash FROM users WHERE id=?').get(userId).password_hash;assert.match(savedPassword,/^scrypt:/);assert.equal(savedPassword.includes('Updated-Member-Pass-123'),false);
  assert.equal((await call('/api/auth/login',{method:'POST',body:{email:'one@skillswap.test',password:'Member-Pass-12345'}})).status,401);
  assert.equal((await call('/api/auth/login',{method:'POST',body:{email:'one@skillswap.test',password:'Updated-Member-Pass-123'}})).status,200);
  const reportUser=await call('/api/reports',{method:'POST',cookie:userCookie,body:{targetType:'USER',targetId:otherId,reason:'Harassment',description:'Repeated unwanted messages in this exchange.'}});assert.equal(reportUser.status,201);const reportId=reportUser.data.item.id;
  assert.equal((await call('/api/reports',{method:'POST',cookie:userCookie,body:{targetType:'USER',targetId:otherId,reason:'Harassment',description:'This duplicate report should be rejected.'}})).status,409);
  assert.equal((await call('/api/reports',{method:'POST',cookie:userCookie,body:{targetType:'USER',targetId:userId,reason:'Other',description:'This should not allow reporting yourself.'}})).status,400);
  const reportSwap=await call('/api/reports',{method:'POST',cookie:userCookie,body:{targetType:'SWAP',targetId:swapId,reason:'Spam',description:'The exchange request contains unsolicited spam.'}});assert.equal(reportSwap.status,201);
  const reportMessage=await call('/api/reports',{method:'POST',cookie:userCookie,body:{targetType:'MESSAGE',targetId:messageId,reason:'Harassment',description:'This message requests an unsafe action.'}});assert.equal(reportMessage.status,201);
  for(let i=0;i<2;i++)database.prepare("INSERT INTO reports(id,status,reporter_id,reported_user_id,reason,description) VALUES(?,'OPEN',?,?,?,?)").run(randomUUID(),userId,otherId,'Spam','Existing report for rate limit coverage.');
  assert.equal((await call('/api/reports',{method:'POST',cookie:userCookie,body:{targetType:'USER',targetId:otherId,reason:'Suspicious activity',description:'Repeated messages need moderator attention.'}})).status,429);
  assert.equal((await call('/api/admin/reports',{cookie:userCookie})).status,403);
  const reports=await call('/api/admin/reports?status=OPEN&page=1',{cookie:adminCookie});assert.equal(reports.status,200);assert.equal(reports.data.pagination.total,5);
  const reportDetail=await call(`/api/admin/reports/${reportId}`,{cookie:adminCookie});assert.equal(reportDetail.status,200);assert.equal(reportDetail.data.item.reportedUserId,otherId);
  assert.equal((await call(`/api/admin/reports/${reportId}/review`,{method:'PATCH',cookie:adminCookie,body:{adminNote:'Reviewing the conversation context.'}})).data.status,'UNDER_REVIEW');
  assert.equal((await call(`/api/admin/reports/${reportId}/resolve`,{method:'PATCH',cookie:adminCookie,body:{adminNote:'Reviewed and resolved.'}})).data.status,'RESOLVED');
  const dismissId=reportMessage.data.item.id;assert.equal((await call(`/api/admin/reports/${dismissId}/dismiss`,{method:'PATCH',cookie:adminCookie,body:{adminNote:'No policy issue was found.'}})).data.status,'DISMISSED');
  assert.equal((await call(`/api/admin/swaps/${swapId}`,{cookie:adminCookie})).status,200);assert.equal((await call('/api/admin/swaps?status=PENDING',{cookie:adminCookie})).data.pagination.total,1);
  database.prepare("INSERT INTO payments(id,user_id,swap_request_id,amount,currency,status,provider,description) VALUES(?,?,?,500,'INR','FAILED','test','Test payment')").run(randomUUID(),userId,swapId);
  const payments=await call('/api/admin/payments?status=FAILED',{cookie:adminCookie});assert.equal(payments.status,200);assert.equal(payments.data.items.length,1);assert.equal(payments.data.items[0].amount,500);
  const logs=await call('/api/admin/audit-logs?action=USER_SUSPENDED',{cookie:adminCookie});assert.equal(logs.status,200);assert.ok(logs.data.items.some(x=>x.targetId===userId));assert.equal((await call('/api/admin/audit-logs',{cookie:userCookie})).status,403);
  const verifyLogs=await call('/api/admin/audit-logs?action=USER_VERIFIED',{cookie:adminCookie});assert.ok(verifyLogs.data.items.some(x=>x.targetId===userId));
  const settings=await call('/api/admin/settings',{cookie:adminCookie});assert.equal(settings.status,200);assert.equal(JSON.stringify(settings.data).includes(secret),false);

  assert.equal((await call('/api/skills/user',{method:'POST',cookie:second.cookie,body:{skillId:pairs[10].offered,type:'LEARN',level:'BEGINNER'}})).status,201);
  const readChunk=reader=>{let timer;return Promise.race([reader.read(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('Timed out waiting for a live event.')),3000)})]).finally(()=>clearTimeout(timer));};
  const eventController=new AbortController();streamControllers.push(eventController);
  const eventResponse=await fetch(base+'/api/realtime/events',{headers:{cookie:userCookie},signal:eventController.signal});assert.equal(eventResponse.status,200);assert.match(eventResponse.headers.get('content-type')||'',/text\/event-stream/);
  const eventReader=eventResponse.body.getReader(),decoder=new TextDecoder();assert.match(decoder.decode((await readChunk(eventReader)).value),/retry: 3000/);
  const notificationPromise=readChunk(eventReader);
  const workflowRequest=await call('/api/swap-requests',{method:'POST',cookie:second.cookie,body:{receiverId:userId,skillOfferedId:pairs[10].wanted,skillWantedId:pairs[10].offered,message:'Let us complete an end-to-end exchange.'}});assert.equal(workflowRequest.status,201);const workflowId=workflowRequest.data.item.id;
  assert.match(decoder.decode((await notificationPromise).value),/"type":"NOTIFICATION_CREATED"/);eventController.abort();await new Promise(resolve=>setTimeout(resolve,100));
  assert.equal((await call(`/api/swap-requests/${workflowId}/accept`,{method:'PATCH',cookie:userCookie})).data.status,'ACCEPTED');
  const started=await call(`/api/swap-requests/${workflowId}/start`,{method:'PATCH',cookie:second.cookie});assert.equal(started.status,200);assert.equal(started.data.status,'IN_PROGRESS');
  assert.equal((await call(`/api/swap-requests/${workflowId}`,{cookie:second.cookie})).status,200);
  const outsider=await call(`/api/swap-requests/${workflowId}`,{cookie:outsiderCookie});assert.equal(outsider.status,404);
  const reconnectController=new AbortController();streamControllers.push(reconnectController);
  const reconnectResponse=await fetch(base+'/api/realtime/events',{headers:{cookie:userCookie},signal:reconnectController.signal});assert.equal(reconnectResponse.status,200);
  const reconnectReader=reconnectResponse.body.getReader();assert.match(decoder.decode((await readChunk(reconnectReader)).value),/retry: 3000/);
  const messagePromise=readChunk(reconnectReader);assert.equal((await call(`/api/conversations/${started.data.conversationId}/messages`,{method:'POST',cookie:second.cookie,body:{content:'Realtime QA message'}})).status,201);
  assert.match(decoder.decode((await messagePromise).value),/"type":"MESSAGE_CREATED"/);reconnectController.abort();
  const sessionDate=new Date(Date.now()+5*86400000).toISOString().slice(0,10);
  const proposed=await call('/api/sessions',{method:'POST',cookie:second.cookie,body:{swapRequestId:workflowId,date:sessionDate,startTime:'10:00',endTime:'11:00',timezone:'UTC',notes:'Workflow QA session'}});assert.equal(proposed.status,201);const sessionId=proposed.data.item.id;
  assert.equal((await call('/api/sessions',{method:'POST',cookie:userCookie,body:{swapRequestId:workflowId,date:sessionDate,startTime:'10:30',endTime:'11:30',timezone:'UTC'}})).status,409);
  assert.equal((await call('/api/sessions',{method:'POST',cookie:userCookie,body:{swapRequestId:workflowId,date:sessionDate,startTime:'25:00',endTime:'26:00',timezone:'UTC'}})).status,400);
  assert.equal((await call(`/api/sessions/${sessionId}/accept`,{method:'POST',cookie:userCookie})).data.item.status,'CONFIRMED');
  const scheduled=await call(`/api/sessions/${sessionId}`,{cookie:userCookie});assert.equal(scheduled.status,200);
  assert.equal((await call(`/api/sessions/${sessionId}`,{cookie:(await call('/api/auth/login',{method:'POST',body:{email:'outsider@skillswap.test',password:'Member-Pass-12345'}})).cookie})).status,404);
  assert.equal((await call(`/api/sessions/${sessionId}/complete`,{method:'POST',cookie:second.cookie})).data.completed,false);
  assert.equal((await call(`/api/sessions/${sessionId}/complete`,{method:'POST',cookie:userCookie})).data.completed,true);
  assert.equal((await call(`/api/swap-requests/${workflowId}/complete`,{method:'POST',cookie:second.cookie})).data.completed,false);
  assert.equal((await call(`/api/swap-requests/${workflowId}/complete`,{method:'POST',cookie:userCookie})).data.status,'COMPLETED');
  assert.equal((await call('/api/reviews',{method:'POST',cookie:second.cookie,body:{revieweeId:userId,swapRequestId:workflowId,rating:5,comment:'Completed end-to-end test exchange.'}})).status,201);
  assert.ok(database.prepare("SELECT COUNT(*) AS n FROM notifications WHERE user_id=? AND related_swap_request_id=?").get(userId,workflowId).n>0);
  const subscriptionPaymentId=randomUUID();database.prepare("INSERT INTO payments(id,user_id,amount,currency,status,provider,description) VALUES(?,?,2000,'INR','SUCCESS','test','Subscription regression test')").run(subscriptionPaymentId,userId);
  database.prepare("INSERT INTO subscriptions(id,user_id,plan,amount,currency,status,start_at,end_at,payment_id,provider) VALUES(?,?,'WEEKLY',2000,'INR','ACTIVE',?,?,?,'test')").run(randomUUID(),userId,'2026-10-01T00:00:00.000Z','2099-10-08T00:00:00.000Z',subscriptionPaymentId);
  assert.equal((await call('/api/subscriptions/current',{cookie:userCookie})).data.active,true);
  database.prepare("UPDATE subscriptions SET end_at='2000-01-01T00:00:00.000Z' WHERE user_id=?").run(userId);
  const expiredSubscription=await call('/api/subscriptions/current',{cookie:userCookie});assert.equal(expiredSubscription.data.active,false);assert.equal(expiredSubscription.data.item.status,'EXPIRED');
  database.prepare('INSERT INTO user_skills(id,user_id,skill_id,type,level) VALUES(?,?,?,\'TEACH\',\'BEGINNER\')').run(randomUUID(),outsiderRegistration.data.user.id,skill2);
  const retainedPaymentId=randomUUID();database.prepare("INSERT INTO payments(id,user_id,amount,currency,status,provider,description) VALUES(?, ?, 100,'INR','SUCCESS','test','Retained history')").run(retainedPaymentId,outsiderRegistration.data.user.id);
  assert.equal((await call(`/api/admin/users/${outsiderRegistration.data.user.id}/remove`,{method:'DELETE',cookie:userCookie})).status,403);
  assert.equal((await call(`/api/admin/users/${adminId}/remove`,{method:'DELETE',cookie:adminCookie})).status,409);
  const removed=await call(`/api/admin/users/${outsiderRegistration.data.user.id}/remove`,{method:'DELETE',cookie:adminCookie});assert.equal(removed.status,200);assert.equal(removed.data.status,'removed');
  const removedRow=database.prepare('SELECT status,deleted_at AS deletedAt,name,bio,avatar FROM users WHERE id=?').get(outsiderRegistration.data.user.id);assert.equal(removedRow.status,'suspended');assert.ok(removedRow.deletedAt);assert.equal(removedRow.name,'Removed user');assert.equal(removedRow.bio,'');assert.equal(removedRow.avatar,null);
  assert.equal(database.prepare('SELECT COUNT(*) AS n FROM user_skills WHERE user_id=?').get(outsiderRegistration.data.user.id).n,1);assert.equal(database.prepare('SELECT COUNT(*) AS n FROM payments WHERE id=?').get(retainedPaymentId).n,1);
  assert.equal(database.prepare('SELECT COUNT(*) AS n FROM sessions WHERE user_id=?').get(outsiderRegistration.data.user.id).n,0);
  assert.equal((await call('/api/auth/session',{cookie:outsiderCookie})).status,401);
  assert.equal((await call('/api/auth/login',{method:'POST',body:{email:'outsider@skillswap.test',password:'Member-Pass-12345'}})).data.error,'This account is no longer available. Please contact support if you believe this was a mistake.');
  assert.equal((await call(`/api/admin/users/${outsiderRegistration.data.user.id}/activate`,{method:'PATCH',cookie:adminCookie})).status,409);
  const removedFilter=await call('/api/admin/users?status=removed',{cookie:adminCookie});assert.ok(removedFilter.data.items.some(item=>item.id===outsiderRegistration.data.user.id&&item.status==='removed'));
  const removedAudit=await call('/api/admin/audit-logs?action=USER_REMOVED',{cookie:adminCookie});assert.ok(removedAudit.data.items.some(item=>item.targetId===outsiderRegistration.data.user.id));
  assert.equal((await call('/api/auth/logout',{method:'POST',cookie:userCookie})).status,200);
  assert.equal((await call('/api/auth/session',{cookie:userCookie})).status,401);
  database.close();
});
