import type { ReactNode } from 'react';
import SkillSelector from './SkillSelector';
import UserSkillCard from './UserSkillCard';
import type { SkillKind, UserSkill } from '../types';

export function ProfileHeader({ name, avatar, subtitle, action, verified=false }: { name:string; avatar:string|null; subtitle?:string; action?:ReactNode;verified?:boolean }) {
  return <section className="flex flex-col items-center gap-5 rounded-3xl bg-gradient-to-br from-brand-700 to-brand-500 p-7 text-center text-white shadow-sm sm:flex-row sm:text-left"><div className="grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-full border-4 border-white/70 bg-white/20 text-3xl font-bold">{avatar?<img src={avatar} alt={`${name}'s profile`} className="h-full w-full object-cover"/>:name.slice(0,1).toUpperCase()}</div><div className="min-w-0 flex-1"><h1 className="text-2xl font-extrabold sm:text-3xl">{name}{verified&&<span title="Profile verified by SkillSwap" aria-label="Verified profile" className="ml-2 inline-flex items-center rounded-full bg-white/20 px-2 py-0.5 align-middle text-sm">✓ Verified</span>}</h1>{subtitle&&<p className="mt-1 text-sm text-white/80">{subtitle}</p>}</div>{action}</section>;
}
export function ProfileCompletion({ value }: { value:number }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between gap-3"><h2 className="font-bold text-slate-900">Profile completion</h2><span className="font-semibold text-brand-700">{value}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand-500" style={{width:`${value}%`}}/></div><p className="mt-2 text-sm text-slate-500">Fill in a few details to help others understand your skills. This is a checklist, not a measure of quality.</p></section>; }
export function SkillLevel({ level }: { level:string }) { return <span className="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-semibold text-brand-700">{level[0]+level.slice(1).toLowerCase()}</span>; }
export function SkillBadge({ name, level, category }: {name:string;level:string;category?:string}) { return <article className="flex min-w-0 items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-4"><div className="min-w-0"><p className="truncate font-semibold text-slate-900">{name}</p>{category&&<p className="text-xs text-slate-500">{category}</p>}</div><SkillLevel level={level}/></article>; }
export function ProfileInfo({ bio, college, location, website, email }: {bio:string;college:string;location?:string;website?:string;email?:string}) { return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">About me</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{bio||'This member has not added a bio yet.'}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-500">{college&&<span>🎓 {college}</span>}{location&&<span>📍 {location}</span>}{website&&<a className="text-brand-700 hover:underline" href={website} target="_blank" rel="noreferrer">Website ↗</a>}{email&&<a className="text-brand-700 hover:underline" href={`mailto:${email}`}>{email}</a>}</div></section>; }
export function LearningGoals({ goals }: { goals:string }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">Learning goals</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{goals||'No learning goals added yet.'}</p></section>; }
export function PrivacySettings({ visibility, showEmail, onVisibility, onShowEmail }: {visibility:string;showEmail:boolean;onVisibility:(v:string)=>void;onShowEmail:(v:boolean)=>void}) { return <section className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><h2 className="font-bold">Privacy</h2><div className="mt-3 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Profile visibility<select value={visibility} onChange={e=>onVisibility(e.target.value)} className="mt-1 block w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="PUBLIC">Public</option><option value="USERS">Only SkillSwap users</option><option value="PRIVATE">Private</option></select></label><label className="flex items-center gap-2 self-end pb-2 text-sm"><input type="checkbox" checked={showEmail} onChange={e=>onShowEmail(e.target.checked)} className="h-4 w-4 accent-brand-600"/>Show my email on my profile</label></div></section>; }
export function SkillList({title,type,items,editable,onAdd,onRemove}:{title:string;type:SkillKind;items:UserSkill[];editable?:boolean;onAdd?:(item:{skillId?:string;skillName?:string;type:SkillKind;level:UserSkill['level']})=>Promise<void>;onRemove?:(id:string)=>Promise<void>}) { return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">{title}</h2>{editable&&onAdd&&<div className="mt-4"><SkillSelector type={type} existingSkillIds={items.map(s=>s.skillId)} onAdd={onAdd}/></div>}<div className="mt-3 grid gap-3 sm:grid-cols-2">{items.map(item=>editable&&onRemove?<UserSkillCard key={item.id} item={item} onRemove={onRemove}/>:<SkillBadge key={item.id||item.skillId} name={item.name} level={item.level} category={item.category}/>)}</div>{items.length===0&&<p className="mt-3 text-sm text-slate-500">{editable?'Add a skill to get started.':'No skills listed.'}</p>}</section>; }
