import { useEffect, useState } from 'react';
import { apiRequest } from '../service/api';

type Slot={id:string;dayOfWeek:number;startTime:string;endTime:string;timezone:string;isActive:boolean};
type Settings={timezone:string;visibility:'PUBLIC'|'MATCHES'|'PARTNERS'};
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const browserZone=()=>{try{return Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';}catch{return 'UTC';}};

export default function AvailabilityPage(){
  const [settings,setSettings]=useState<Settings>({timezone:browserZone(),visibility:'MATCHES'}),[slots,setSlots]=useState<Slot[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [day,setDay]=useState(1),[start,setStart]=useState('09:00'),[end,setEnd]=useState('10:00'),[editing,setEditing]=useState<string|null>(null);
  async function load(){const data=await apiRequest<{settings:Settings;items:Slot[]}>(`/api/availability/me?timezone=${encodeURIComponent(browserZone())}`);setSettings(data.settings);setSlots(data.items);}
  useEffect(()=>{void load().catch(e=>setError(e.message||'Could not load availability.')).finally(()=>setLoading(false));},[]);
  async function saveSettings(){setBusy(true);setError('');setNotice('');try{const result=await apiRequest<{settings:Settings}>('/api/availability/settings',{method:'PATCH',body:JSON.stringify(settings)});setSettings(result.settings);setNotice('Your privacy and time zone settings are saved.');}catch(e){setError(e instanceof Error?e.message:'Could not save settings.');}finally{setBusy(false);}}
  async function addSlot(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setNotice('');try{const result=await apiRequest<{item:Slot}>('/api/availability',{method:'POST',body:JSON.stringify({dayOfWeek:day,startTime:start,endTime:end,timezone:settings.timezone})});setSlots(current=>[...current,result.item].sort((a,b)=>a.dayOfWeek-b.dayOfWeek||a.startTime.localeCompare(b.startTime)));setNotice('Weekly availability added.');}catch(e){setError(e instanceof Error?e.message:'Could not add this slot.');}finally{setBusy(false);}}
  async function updateSlot(slot:Slot,patch:Partial<Slot>){setBusy(true);setError('');try{const result=await apiRequest<{item:Slot}>(`/api/availability/${encodeURIComponent(slot.id)}`,{method:'PATCH',body:JSON.stringify({...slot,...patch})});setSlots(current=>current.map(item=>item.id===slot.id?{...item,...result.item}:item));setEditing(null);}catch(e){setError(e instanceof Error?e.message:'Could not update this slot.');}finally{setBusy(false);}}
  async function removeSlot(slot:Slot){setBusy(true);setError('');try{await apiRequest(`/api/availability/${encodeURIComponent(slot.id)}`,{method:'DELETE'});setSlots(current=>current.filter(item=>item.id!==slot.id));}catch(e){setError(e instanceof Error?e.message:'Could not remove this slot.');}finally{setBusy(false);}}
  return <main className="mx-auto max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-600">Plan a skill session</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-900">Your availability</h1><p className="mt-2 text-slate-600">Add your usual weekly times so exchange partners can find a slot that works. Your exact schedule is shared only according to your privacy choice.</p>
    {error&&<p role="alert" className="mt-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}{notice&&<p role="status" className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</p>}
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-lg font-bold text-slate-900">Time zone and privacy</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Time zone<input list="timezone-list" value={settings.timezone} onChange={e=>setSettings(s=>({...s,timezone:e.target.value}))} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 font-normal"/><datalist id="timezone-list">{['Asia/Kolkata','UTC','America/New_York','America/Los_Angeles','Europe/London','Europe/Paris','Asia/Singapore','Asia/Tokyo','Australia/Sydney'].map(z=><option key={z} value={z}/>)}</datalist></label><label className="text-sm font-semibold text-slate-700">Who can see your weekly times<select value={settings.visibility} onChange={e=>setSettings(s=>({...s,visibility:e.target.value as Settings['visibility']}))} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 font-normal"><option value="MATCHES">Matches and active exchange partners</option><option value="PARTNERS">Active exchange partners only</option><option value="PUBLIC">Everyone</option></select></label></div><button onClick={()=>void saveSettings()} disabled={busy} className="mt-4 min-h-11 rounded-xl border border-slate-300 px-4 text-sm font-semibold text-slate-700 disabled:opacity-50">Save settings</button><p className="mt-3 text-xs text-slate-500">Your availability is not shown on public profiles. A member who cannot see your schedule will see that it is private.</p></section>
    <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-lg font-bold text-slate-900">Add a weekly time</h2><form onSubmit={e=>void addSlot(e)} className="mt-4 grid gap-3 sm:grid-cols-4"><label className="text-sm font-semibold text-slate-700">Day<select value={day} onChange={e=>setDay(Number(e.target.value))} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3">{days.map((name,index)=><option value={index} key={name}>{name}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Start<input type="time" value={start} onChange={e=>setStart(e.target.value)} required className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3"/></label><label className="text-sm font-semibold text-slate-700">End<input type="time" value={end} onChange={e=>setEnd(e.target.value)} required className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3"/></label><button disabled={busy} className="mt-auto min-h-11 rounded-xl bg-brand-700 px-4 font-semibold text-white disabled:opacity-50">Add time</button></form><p className="mt-3 text-xs text-slate-500">Slots must be 15 minutes to 8 hours. Overlapping times are blocked.</p></section>
    <section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-lg font-bold text-slate-900">Weekly schedule</h2>{loading?<p className="mt-4 animate-pulse text-sm text-slate-500">Loading your schedule…</p>:slots.length===0?<p className="mt-4 rounded-xl bg-slate-50 p-5 text-sm text-slate-600">No weekly times yet. Add one above to help schedule your next exchange.</p>:<ul className="mt-3 divide-y divide-slate-100">{slots.map(slot=><li key={slot.id} className="py-4">{editing===slot.id?<div className="grid gap-3 sm:grid-cols-5"><select aria-label="Day" value={slot.dayOfWeek} onChange={e=>setSlots(s=>s.map(x=>x.id===slot.id?{...x,dayOfWeek:Number(e.target.value)}:x))} className="min-h-11 rounded-xl border px-3">{days.map((name,index)=><option value={index} key={name}>{name}</option>)}</select><input aria-label="Start time" type="time" value={slot.startTime} onChange={e=>setSlots(s=>s.map(x=>x.id===slot.id?{...x,startTime:e.target.value}:x))} className="min-h-11 rounded-xl border px-3"/><input aria-label="End time" type="time" value={slot.endTime} onChange={e=>setSlots(s=>s.map(x=>x.id===slot.id?{...x,endTime:e.target.value}:x))} className="min-h-11 rounded-xl border px-3"/><button disabled={busy} onClick={()=>void updateSlot(slot,{})} className="min-h-11 rounded-xl bg-brand-700 px-3 text-sm font-semibold text-white">Save</button><button onClick={()=>{void load();setEditing(null);}} className="min-h-11 rounded-xl border px-3 text-sm">Discard</button></div>:<div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold text-slate-800">{days[slot.dayOfWeek]} · {slot.startTime}–{slot.endTime}</p><p className="text-xs text-slate-500">{slot.timezone}{slot.isActive?'':' · Paused'}</p></div><div className="flex gap-2"><button disabled={busy} onClick={()=>void updateSlot(slot,{isActive:!slot.isActive})} className="min-h-10 rounded-lg border px-3 text-sm font-semibold text-slate-700">{slot.isActive?'Pause':'Enable'}</button><button onClick={()=>setEditing(slot.id)} className="min-h-10 rounded-lg border px-3 text-sm font-semibold text-slate-700">Edit</button><button disabled={busy} onClick={()=>void removeSlot(slot)} className="min-h-10 rounded-lg border border-rose-200 px-3 text-sm font-semibold text-rose-700">Remove</button></div></div>}</li>)}</ul>}</section>
  </main>;
}
