import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { apiRequest } from '../service/api';
import type { SkillMatch } from '../types';
import DiscoveryUserCard from '../components/DiscoveryUserCard';
import SkillResultCard from '../components/SkillResultCard';
import RecommendationSection from '../components/recommendations/RecommendationSection';

type SkillResult={skillId:string;name:string;category:string;description:string;teachers:number;learners:number;levels:string[]};
type DiscoveryResponse={success:boolean;people:{results:SkillMatch[];pagination:{page:number;limit:number;total:number;hasNext:boolean}};skills:{results:SkillResult[];pagination:{page:number;limit:number;total:number;hasNext:boolean}};categories:string[]};
type Suggestions={skills:Array<{skillId:string;name:string;category:string}>;people:Array<{id:string;name:string}>};
const sortLabels:{[key:string]:string}={relevance:'Most Relevant',rating:'Highest Rated',newest:'Newest',reviews:'Most Reviews'};
function DiscoverySkeleton(){return <div className="grid gap-4 md:grid-cols-2">{[1,2,3,4].map(n=><div key={n} className="animate-pulse rounded-2xl border border-slate-200 bg-white p-5"><div className="flex gap-3"><div className="h-14 w-14 rounded-full bg-slate-100"/><div className="space-y-2 pt-2"><div className="h-4 w-36 rounded bg-slate-100"/><div className="h-3 w-24 rounded bg-slate-100"/></div></div><div className="mt-5 h-16 rounded bg-slate-50"/></div>)}</div>}
export default function FindSkillsPage(){
  const [params,setParams]=useSearchParams(),[draft,setDraft]=useState(params.get('q')||''),[data,setData]=useState<DiscoveryResponse|null>(null),[suggestions,setSuggestions]=useState<Suggestions>({skills:[],people:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filtersOpen,setFiltersOpen]=useState(false),[suggestOpen,setSuggestOpen]=useState(false),[retry,setRetry]=useState(0);
  const q=params.get('q')||'',type=params.get('type')==='skills'?'skills':'people',page=Math.max(1,Number(params.get('page')||'1')||1);
  const queryString=useMemo(()=>{const query=new URLSearchParams(params);query.set('type','all');query.set('page',String(page));query.set('limit','20');return query.toString()},[params,page]);
  useEffect(()=>setDraft(q),[q]);
  useEffect(()=>{let live=true;setLoading(true);setError('');const timer=window.setTimeout(()=>{apiRequest<DiscoveryResponse>(`/api/discovery?${queryString}`).then(result=>{if(live)setData(result)}).catch(e=>{if(live)setError(e instanceof Error?e.message:'Unable to load search results. Please try again.')}).finally(()=>{if(live)setLoading(false)})},250);return()=>{live=false;window.clearTimeout(timer)}},[queryString,retry]);
  useEffect(()=>{const term=draft.trim();if(term.length<2){setSuggestions({skills:[],people:[]});return}let live=true;const timer=window.setTimeout(()=>{apiRequest<Suggestions>(`/api/discovery?type=suggestions&q=${encodeURIComponent(term)}`).then(value=>{if(live)setSuggestions(value)}).catch(()=>{if(live)setSuggestions({skills:[],people:[]})})},320);return()=>{live=false;window.clearTimeout(timer)}},[draft]);
  function patch(values:Record<string,string|null>,replace=false){const next=new URLSearchParams(params);for(const [key,value]of Object.entries(values)){if(value)next.set(key,value);else next.delete(key)}next.set('page','1');setParams(next,{replace});}
  function submit(e?:FormEvent){e?.preventDefault();patch({q:draft.trim()||null},false);setSuggestOpen(false)}
  function clearAll(){const next=new URLSearchParams();if(type==='skills')next.set('type','skills');setParams(next);setDraft('');setSuggestions({skills:[],people:[]})}
  function chooseSuggestion(value:string,kind:'skills'|'people'){setDraft(value);const next=new URLSearchParams(params);next.set('q',value);next.set('type',kind);next.set('page','1');setParams(next);setSuggestOpen(false)}
  function changePage(value:number){patch({page:String(value)})}
  const activeChips=[...(q?[{key:'q',label:q}]:[]),...(params.get('category')?[{key:'category',label:params.get('category')!}]:[]),...(params.get('level')?[{key:'level',label:params.get('level')!.toLowerCase().replace(/^./,x=>x.toUpperCase())}]:[]),...(params.get('intent')&&params.get('intent')!=='all'?[{key:'intent',label:params.get('intent')==='teach'?'Can teach me':params.get('intent')==='learn'?'Wants to learn from me':'Mutual exchange'}]:[]),...(params.get('rating')?[{key:'rating',label:`${params.get('rating')}+ ★`}]:[]),...(params.get('location')?[{key:'location',label:params.get('location')!}]:[]),...(params.get('sort')&&params.get('sort')!=='relevance'?[{key:'sort',label:sortLabels[params.get('sort')!]||params.get('sort')!}]:[])];
  const filters=<div className="space-y-5"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-900">Filters</h2><button onClick={clearAll} className="text-xs font-semibold text-brand-700 hover:underline">Clear filters</button></div>
    <label className="block text-sm font-semibold text-slate-700">Category<select value={params.get('category')||''} onChange={e=>patch({category:e.target.value||null})} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">All categories</option>{(data?.categories||[]).map(c=><option key={c} value={c}>{c}</option>)}</select></label>
    <label className="block text-sm font-semibold text-slate-700">Skill Level<select value={params.get('level')||''} onChange={e=>patch({level:e.target.value||null})} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">All levels</option>{[['BEGINNER','Beginner'],['INTERMEDIATE','Intermediate'],['ADVANCED','Advanced'],['EXPERT','Expert']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
    <label className="block text-sm font-semibold text-slate-700">Looking For<select value={params.get('intent')||'all'} onChange={e=>patch({intent:e.target.value==='all'?null:e.target.value})} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="all">All people</option><option value="teach">People who can teach me</option><option value="learn">People who want to learn from me</option><option value="mutual">Mutual skill exchange</option></select></label>
    <label className="block text-sm font-semibold text-slate-700">Minimum Rating<select value={params.get('rating')||''} onChange={e=>patch({rating:e.target.value||null})} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Any rating</option>{['3','3.5','4','4.5'].map(v=><option key={v} value={v}>{v}+ stars</option>)}</select></label>
    <label className="block text-sm font-semibold text-slate-700">Location<input value={params.get('location')||''} onChange={e=>patch({location:e.target.value||null})} placeholder="City or region" maxLength={80} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label>
    <label className="block text-sm font-semibold text-slate-700">Sort By<select value={params.get('sort')||'relevance'} onChange={e=>patch({sort:e.target.value==='relevance'?null:e.target.value})} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">{Object.entries(sortLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>
  </div>;
  const results=type==='skills'?data?.skills.results||[]:data?.people.results||[],pagination=type==='skills'?data?.skills.pagination:data?.people.pagination,total=type==='skills'?data?.skills.pagination.total:data?.people.pagination.total;
  return <main className="mx-auto max-w-7xl"><header className="mb-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-600">Make a connection</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-900 sm:text-4xl">Find Your Skill Partner</h1><p className="mt-2 max-w-2xl text-slate-500">Discover people who can teach what you want to learn — and learn from you in return.</p></header>
    <form onSubmit={submit} className="relative flex gap-2"><div className="relative min-w-0 flex-1"><span aria-hidden="true" className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-lg text-slate-400">⌕</span><input value={draft} onFocus={()=>setSuggestOpen(true)} onBlur={()=>window.setTimeout(()=>setSuggestOpen(false),160)} onChange={e=>setDraft(e.target.value)} placeholder="Search skills or people..." maxLength={80} className="min-h-12 w-full rounded-xl border border-slate-200 bg-white pl-11 pr-10 text-sm shadow-sm outline-none focus:border-brand-500 focus:ring-4 focus:ring-brand-100"/><button type="button" aria-label="Clear search" onMouseDown={e=>e.preventDefault()} onClick={()=>{setDraft('');patch({q:null})}} className={`${draft?'':'hidden'} absolute right-3 top-1/2 -translate-y-1/2 text-lg text-slate-400`}>×</button>{suggestOpen&&(suggestions.skills.length>0||suggestions.people.length>0)&&<div className="absolute z-30 mt-2 max-h-72 w-full overflow-auto rounded-xl border border-slate-200 bg-white p-2 shadow-xl">{suggestions.skills.length>0&&<><p className="px-3 py-1 text-[11px] font-bold uppercase text-slate-400">Skills</p>{suggestions.skills.map(s=><button type="button" key={s.skillId} onMouseDown={e=>e.preventDefault()} onClick={()=>chooseSuggestion(s.name,'skills')} className="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-50">{s.name}<span className="ml-2 text-xs text-slate-400">{s.category}</span></button>)}</>}{suggestions.people.length>0&&<><p className="px-3 py-1 text-[11px] font-bold uppercase text-slate-400">People</p>{suggestions.people.map(p=><button type="button" key={p.id} onMouseDown={e=>e.preventDefault()} onClick={()=>chooseSuggestion(p.name,'people')} className="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-50">{p.name}</button>)}</>}</div>}</div><button className="min-h-12 shrink-0 rounded-xl bg-brand-700 px-5 text-sm font-bold text-white hover:bg-brand-800">Search</button></form>
    {(!q||type==='people')&&<div className="mt-5"><RecommendationSection mode={q?'users':'all'} title={q?'People who may be a good match':'Recommended for You'}/></div>}
    <div className="mt-5 flex flex-wrap items-center gap-2"><span className="mr-1 text-xs font-semibold text-slate-400">Try:</span>{['Python','Cybersecurity','Canva','Web Development','Arun','UI/UX'].map(v=><button key={v} onClick={()=>chooseSuggestion(v,/^(Arun|Priya|Sathish)$/i.test(v)?'people':'skills')} className="rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-600 hover:border-brand-300 hover:text-brand-700">{v}</button>)}</div>
    <div className="mt-7 flex flex-wrap items-center justify-between gap-3 border-b border-slate-200"><div role="tablist" aria-label="Discovery result type" className="flex gap-5">{(['skills','people'] as const).map(t=><button key={t} role="tab" aria-selected={type===t} onClick={()=>patch({type:t==='people'?null:t})} className={`min-h-11 border-b-2 px-1 text-sm font-bold capitalize ${type===t?'border-brand-600 text-brand-700':'border-transparent text-slate-500'}`}>{t}<span className="ml-2 rounded-full bg-slate-100 px-2 py-0.5 text-xs">{t==='skills'?data?.skills.pagination.total??'—':data?.people.pagination.total??'—'}</span></button>)}</div><button onClick={()=>setFiltersOpen(true)} className="mb-2 inline-flex min-h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold lg:hidden">☷ Filters{activeChips.length>0&&<span className="rounded-full bg-brand-100 px-2 text-xs text-brand-800">{activeChips.length}</span>}</button></div>
    <div className="mt-5 grid items-start gap-5 lg:grid-cols-[240px_minmax(0,1fr)]"><aside className="hidden rounded-2xl border border-slate-200 bg-white p-5 lg:block">{filters}</aside><section className="min-w-0"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><p className="text-sm text-slate-500">{loading?'Searching…':`${total||0} ${type} found`}</p>{activeChips.length>0&&<button onClick={clearAll} className="text-xs font-bold text-brand-700 hover:underline">Clear all</button>}</div>{activeChips.length>0&&<div className="mb-4 flex flex-wrap gap-2">{activeChips.map(chip=><button key={chip.key} onClick={()=>patch({[chip.key]:null})} className="rounded-full bg-brand-50 px-3 py-1.5 text-xs font-semibold text-brand-800">{chip.label} ×</button>)}</div>}
      {error?<div role="alert" className="rounded-2xl border border-rose-100 bg-white p-8 text-center"><p className="font-semibold text-slate-900">Unable to load search results.</p><p className="mt-1 text-sm text-slate-500">Please try again.</p><button onClick={()=>setRetry(n=>n+1)} className="mt-4 min-h-10 rounded-lg bg-brand-700 px-4 text-sm font-bold text-white">Try again</button></div>:loading||!data?<DiscoverySkeleton/>:results.length===0?<div className="rounded-2xl border border-slate-200 bg-white p-9 text-center"><h2 className="text-lg font-bold text-slate-900">No matches found.</h2><p className="mt-2 text-sm text-slate-500">Try removing some filters, searching another skill, or using a broader keyword.</p><div className="mt-4 flex justify-center gap-2"><button onClick={clearAll} className="min-h-10 rounded-lg border border-slate-200 px-4 text-sm font-semibold">Clear filters</button><button onClick={()=>{patch({q:null,type:'skills'});setDraft('')}} className="min-h-10 rounded-lg bg-brand-700 px-4 text-sm font-semibold text-white">Browse popular skills</button></div></div>:<><div className="grid min-w-0 gap-4 md:grid-cols-2">{type==='skills'?(results as SkillResult[]).map(s=><SkillResultCard key={s.skillId} skill={s}/>):(results as SkillMatch[]).map(m=><DiscoveryUserCard key={m.user.id} match={m}/>)}</div><div className="mt-6 flex items-center justify-between"><button disabled={page<=1||loading} onClick={()=>changePage(page-1)} className="min-h-10 rounded-xl border border-slate-200 px-4 text-sm font-semibold disabled:opacity-40">Previous</button><span className="text-sm text-slate-500">Page {page} of {Math.max(1,Math.ceil((total||0)/20))}</span><button disabled={!pagination?.hasNext||loading} onClick={()=>changePage(page+1)} className="min-h-10 rounded-xl border border-slate-200 px-4 text-sm font-semibold disabled:opacity-40">Next</button></div></>}
    </section></div>
    {filtersOpen&&<div className="fixed inset-0 z-50 bg-slate-950/40 lg:hidden" onMouseDown={e=>{if(e.target===e.currentTarget)setFiltersOpen(false)}}><section role="dialog" aria-modal="true" aria-label="Discovery filters" className="absolute inset-y-0 right-0 w-[min(88vw,380px)] overflow-y-auto bg-white p-5 shadow-xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">Filters</h2><button onClick={()=>setFiltersOpen(false)} aria-label="Close filters" className="grid h-10 w-10 place-items-center rounded-lg border">×</button></div>{filters}<button onClick={()=>setFiltersOpen(false)} className="mt-6 min-h-11 w-full rounded-xl bg-brand-700 font-bold text-white">Show results</button></section></div>}
  </main>;
}
