import { useCallback, useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { apiRequest } from '../service/api';
import { PaymentCard, PaymentEmptyState, PaymentHistory, PaymentSkeleton } from '../components/payments/Payments';
import type { Payment } from '../components/payments/Payments';
import { useRealtimeEvent } from '../realtime/events';

type Filter='ALL'|'SUCCESS'|'PENDING'|'FAILED'|'REFUNDED';
const filters:Filter[]=['ALL','SUCCESS','PENDING','FAILED','REFUNDED'];
export default function PaymentsPage(){const [search]=useSearchParams(),selectedId=search.get('id'),[filter,setFilter]=useState<Filter>('ALL'),[items,setItems]=useState<Payment[]>([]),[selected,setSelected]=useState<Payment|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');try{if(selectedId){const response=await apiRequest<{item:Payment}>(`/api/payments/${encodeURIComponent(selectedId)}`);setSelected(response.item);}else{const response=await apiRequest<{items:Payment[]}>(`/api/payments?status=${filter}`);setItems(response.items);}}catch(e){setError(e instanceof Error?e.message:'Could not load payment history.');}finally{setLoading(false);}},[filter,selectedId]);useEffect(()=>{void load();},[load]);useRealtimeEvent('NOTIFICATION_CREATED',()=>void load());
  return <main className="mx-auto max-w-5xl"><Link to="/dashboard" className="text-sm font-semibold text-brand-700 hover:underline">← Dashboard</Link><div className="mt-3 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-600">Secure transactions</p><h1 className="mt-2 text-3xl font-extrabold text-slate-900">Payment history</h1><p className="mt-2 text-slate-600">View payment status and references for your SkillSwap sessions.</p><p className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">SkillSwap never needs your payment password or card PIN. Payment amounts and status are confirmed by the payment provider.</p></div><Link to="/sessions" className="inline-flex min-h-10 items-center rounded-xl border border-slate-300 px-4 text-sm font-semibold text-slate-700">View sessions</Link></div>{!selectedId&&<div role="tablist" aria-label="Filter payments" className="mt-6 flex gap-2 overflow-x-auto border-b border-slate-200">{filters.map(value=><button key={value} role="tab" aria-selected={filter===value} onClick={()=>setFilter(value)} className={`min-h-11 shrink-0 border-b-2 px-3 text-sm font-semibold ${filter===value?'border-brand-600 text-brand-700':'border-transparent text-slate-500'}`}>{value==='ALL'?'All':value[0]+value.slice(1).toLowerCase()}</button>)}</div>}{error&&<div role="alert" className="mt-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}<button onClick={()=>void load()} className="ml-2 font-bold underline">Try again</button></div>}{loading?<div className="mt-5"><PaymentSkeleton/></div>:selectedId?(selected?<div className="mt-5"><PaymentCard payment={selected}/>{selected.sessionId&&<p className="mt-4 text-sm text-slate-600">This payment belongs to session scheduled on {selected.sessionStartAt?new Date(selected.sessionStartAt).toLocaleString():selected.sessionId}.</p>}</div>:<div className="mt-5 rounded-xl bg-slate-50 p-5 text-slate-600">Payment not found.</div>):items.length?<div className="mt-5"><PaymentHistory items={items}/></div>:<div className="mt-5"><PaymentEmptyState/></div>}
  </main>;
}
