import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { apiRequest } from '../service/api';
import type { SkillKind, SkillMatch, UserSkill } from '../types';
import AvatarUpload from '../components/AvatarUpload';
import ProfileEditForm from '../components/ProfileEditForm';
import SwapRequestButton from '../components/SwapRequestButton';
import OpenConversationButton from '../components/messaging/OpenConversationButton';
import { LearningGoals, ProfileCompletion, ProfileHeader, ProfileInfo, PrivacySettings, SkillBadge, SkillList } from '../components/ProfileComponents';
import ProfileReviews from '../components/reviews/ProfileReviews';
import ReportControl from '../components/admin/ReportControl';
import BlockUserButton from '../components/BlockUserButton';

type Profile = {id:string;name:string;email?:string;avatar:string|null;bio:string;college:string;location?:string;website?:string;learningGoals:string;profileVisibility?:string;showEmail?:boolean;verificationStatus?:string;showReviews?:boolean;createdAt?:string;updatedAt?:string;skills:UserSkill[];completion:number;activity?:{teachingSkills:number;learningSkills:number;swapRequests:number};matchExplanation?:{directSkills:string[];mutual:boolean}|null};
const sections: {type:SkillKind;title:string}[]=[{type:'TEACH',title:'Skills I can teach'},{type:'LEARN',title:'Skills I want to learn'}];
function completion(p:Profile, skills:UserSkill[]){const fields=[!!p.name.trim(),!!p.avatar,!!p.bio.trim(),!!p.college.trim(),!!p.location?.trim(),skills.some(s=>s.type==='TEACH'),skills.some(s=>s.type==='LEARN'),!!p.learningGoals.trim()];return Math.round(fields.filter(Boolean).length/fields.length*100);}

export function OwnProfilePage(){
  const [profile,setProfile]=useState<Profile|null>(null); const [skills,setSkills]=useState<UserSkill[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState(true);
  async function refresh(){const [p,s]=await Promise.all([apiRequest<{profile:Profile}>('/api/profile/me'),apiRequest<{items:UserSkill[]}>('/api/skills/user')]);setProfile(p.profile);setSkills(s.items);}
  useEffect(()=>{refresh().catch(e=>setError(e.message||'Could not load your profile.')).finally(()=>setBusy(false));},[]);
  async function add(item:{skillId?:string;skillName?:string;type:SkillKind;level:UserSkill['level']}){const r=await apiRequest<{item:UserSkill}>('/api/skills/user',{method:'POST',body:JSON.stringify(item)});setSkills(s=>[...s,r.item]);}
  async function remove(id:string){await apiRequest('/api/skills/user/'+encodeURIComponent(id),{method:'DELETE'});setSkills(s=>s.filter(i=>i.id!==id));}
  if(busy)return <p className="py-12 text-center text-slate-500">Loading your profile…</p>;
  if(!profile)return <p role="alert" className="rounded-xl bg-rose-50 p-4 text-rose-700">{error||'Could not load your profile.'}</p>;
  return <div className="mx-auto max-w-5xl space-y-5"><ProfileHeader name={profile.name} avatar={profile.avatar} verified={profile.verificationStatus==='VERIFIED'} subtitle={profile.college||'SkillSwap member'} action={<Link to="/profile/edit" className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-brand-700 hover:bg-brand-50">Edit profile</Link>}/>
    {error&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}<ProfileCompletion value={completion(profile,skills)}/>
    <ProfileInfo bio={profile.bio} college={profile.college} location={profile.location} website={profile.website} email={profile.showEmail?profile.email:undefined}/>
    {sections.map(section=><SkillList key={section.type} title={section.title} type={section.type} items={skills.filter(s=>s.type===section.type)} editable onAdd={add} onRemove={remove}/>)}
    <ProfileReviews userId={profile.id} viewerId={profile.id}/>
    <LearningGoals goals={profile.learningGoals}/><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">SkillSwap activity</h2><div className="mt-3 grid grid-cols-3 gap-3 text-center"><Activity label="Teaching skills" count={profile.activity?.teachingSkills||0}/><Activity label="Learning skills" count={profile.activity?.learningSkills||0}/><Activity label="Swap requests" count={profile.activity?.swapRequests||0}/></div><Link to="/swap-requests" className="mt-4 inline-block text-sm font-semibold text-brand-700 hover:underline">View swap requests →</Link></section>
    <p className="text-xs text-slate-400">Profile visibility: {profile.profileVisibility==='USERS'?'Only SkillSwap users':profile.profileVisibility==='PRIVATE'?'Private':'Public'}</p></div>;
}
function Activity({label,count}:{label:string;count:number}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xl font-extrabold text-brand-700">{count}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>}

export function ProfileEditPage(){
  const [p,setP]=useState<Profile|null>(null);const [busy,setBusy]=useState(true);const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState(false);const [error,setError]=useState('');const navigate=useNavigate();
  useEffect(()=>{apiRequest<{profile:Profile}>('/api/profile/me').then(r=>setP(r.profile)).catch(e=>setError(e.message)).finally(()=>setBusy(false));},[]);
  async function upload(file:File){if(!p)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Choose a JPG, PNG, or WEBP image.');return;}if(file.size>5*1024*1024){setError('Choose an image that is 5 MB or smaller.');return;}setUploading(true);setError('');try{const response=await fetch('/api/profile/avatar',{method:'POST',body:file,headers:{'Content-Type':file.type},credentials:'include'});const body=await response.json();if(!response.ok)throw new Error(body.error||'Photo upload failed.');setP({...p,avatar:body.avatar+'?v='+Date.now()});}catch(e){setError(e instanceof Error?e.message:'Photo upload failed.');}finally{setUploading(false);}}
  async function removePhoto(){if(!p)return;setUploading(true);setError('');try{await apiRequest('/api/profile/avatar',{method:'DELETE'});setP({...p,avatar:null});}catch(e){setError(e instanceof Error?e.message:'Could not remove photo.');}finally{setUploading(false);}}
  async function save(e:FormEvent){e.preventDefault();if(!p)return;setSaving(true);setError('');try{await apiRequest('/api/profile/me',{method:'PATCH',body:JSON.stringify({name:p.name,bio:p.bio,college:p.college,location:p.location,website:p.website,learningGoals:p.learningGoals,profileVisibility:p.profileVisibility,showEmail:p.showEmail})});navigate('/profile');}catch(e){setError(e instanceof Error?e.message:'Could not save profile.');}finally{setSaving(false);}}
  if(busy)return <p className="py-12 text-center text-slate-500">Loading profile…</p>;if(!p)return <p role="alert" className="text-rose-700">{error||'Could not load profile.'}</p>;
  const change=(key:'name'|'bio'|'college'|'location'|'website'|'learningGoals',value:string)=>setP({...p,[key]:value});
  return <form onSubmit={save} className="mx-auto max-w-3xl space-y-5"><div><p className="text-xs font-bold uppercase tracking-widest text-brand-600">Your account</p><h1 className="mt-1 text-3xl font-extrabold">Edit profile</h1></div>{error&&<p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
    <AvatarUpload avatar={p.avatar} name={p.name} busy={uploading} onFile={file=>void upload(file)} onRemove={()=>void removePhoto()}/>
    <ProfileEditForm value={{name:p.name,bio:p.bio,college:p.college,location:p.location||'',website:p.website||'',learningGoals:p.learningGoals}} onChange={change}/>
    <PrivacySettings visibility={p.profileVisibility||'PUBLIC'} showEmail={!!p.showEmail} onVisibility={v=>setP({...p,profileVisibility:v})} onShowEmail={v=>setP({...p,showEmail:v})}/><div className="flex flex-wrap justify-end gap-3"><Link to="/profile" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Cancel</Link><button disabled={saving||uploading} className="rounded-xl bg-brand-600 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-60">{saving?'Saving…':'Save changes'}</button></div>
  </form>;
}
export function PublicProfilePage(){
  const {userId=''}=useParams();const [p,setP]=useState<Profile|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(true);const [swapMatch,setSwapMatch]=useState<SkillMatch|null>(null);const [viewerId,setViewerId]=useState('');
  useEffect(()=>{let live=true;Promise.all([apiRequest<{profile:Profile}>(`/api/profile/${encodeURIComponent(userId)}`),apiRequest<{items:UserSkill[]}>('/api/skills/user').catch(()=>({items:[]} as {items:UserSkill[]})),apiRequest<{user:{id:string}}>('/api/auth/session').catch(()=>null)]).then(([r,own,session])=>{if(!live)return;setP(r.profile);setViewerId(session?.user.id||'');const directNames=new Set(r.profile.matchExplanation?.directSkills||[]);const direct=r.profile.skills.filter(s=>s.type==='TEACH'&&directNames.has(s.name));const offered=own.items.filter(s=>s.type==='TEACH');if(direct.length&&offered.length)setSwapMatch({user:{id:r.profile.id,name:r.profile.name,bio:r.profile.bio,avatar:r.profile.avatar},teaches:r.profile.skills.filter(s=>s.type==='TEACH').map(s=>({...s,skillId:s.skillId})),learns:r.profile.skills.filter(s=>s.type==='LEARN').map(s=>({...s,skillId:s.skillId})),directSkills:direct.map(s=>({skillId:s.skillId,name:s.name,category:s.category,yourLevel:'INTERMEDIATE',theirLevel:s.level})),mutualSkills:[],matchType:r.profile.matchExplanation?.mutual?'MUTUAL':'DIRECT',label:r.profile.matchExplanation?.mutual?'Good Match':'Potential Match',offeredSkills:offered.map(s=>({skillId:s.skillId,name:s.name,category:s.category,description:s.description,level:s.level}))});}).catch(e=>{if(live)setError(e.status===404?'This profile is private or unavailable.':e.message||'Could not load this profile.');}).finally(()=>{if(live)setBusy(false);});return()=>{live=false};},[userId]);
  if(busy)return <p className="py-12 text-center text-slate-500">Loading profile…</p>;if(!p)return <div className="mx-auto max-w-2xl rounded-2xl bg-white p-8 text-center"><h1 className="text-2xl font-bold">Profile unavailable</h1><p className="mt-2 text-slate-500">{error}</p><Link to="/matches" className="mt-5 inline-block font-semibold text-brand-700">Back to matches</Link></div>;
  return <div className="mx-auto max-w-5xl space-y-5"><ProfileHeader name={p.name} avatar={p.avatar} verified={p.verificationStatus==='VERIFIED'} subtitle={p.college||'SkillSwap member'} action={viewerId&&viewerId!==p.id?<div className="flex flex-wrap items-center gap-2"><OpenConversationButton userId={p.id} variant="hero"/><ReportControl targetType="USER" targetId={p.id}/><BlockUserButton userId={p.id}/></div>:undefined}/><ProfileInfo bio={p.bio} college={p.college} email={p.email}/>{sections.map(s=><section key={s.type} className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">{s.title}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{p.skills.filter(x=>x.type===s.type).map(x=><SkillBadge key={x.id||x.skillId} name={x.name} level={x.level} category={x.category}/>)}</div>{!p.skills.some(x=>x.type===s.type)&&<p className="mt-2 text-sm text-slate-500">No skills listed.</p>}</section>)}{p.showReviews!==false&&<ProfileReviews userId={p.id} viewerId={viewerId}/>}<LearningGoals goals={p.learningGoals}/>{p.matchExplanation&&<section className="rounded-2xl border border-brand-100 bg-brand-50 p-5"><h2 className="font-bold text-brand-900">Why you match</h2>{p.matchExplanation.mutual&&<p className="mt-2 text-sm text-brand-800">You both have skills that can be exchanged.</p>}{p.matchExplanation.directSkills.length>0&&<p className="mt-2 text-sm text-brand-800">You want to learn {p.matchExplanation.directSkills.join(', ')}. {p.name} can teach {p.matchExplanation.directSkills.join(', ')}.</p>}</section>}{swapMatch&&<section className="rounded-2xl border border-slate-200 bg-white p-5"><SwapRequestButton match={swapMatch}/></section>}</div>;
}
