import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiRequest } from '../service/api';
import { paymentAmountLabel } from '../components/payments/Payments';

type Plan = { plan: 'WEEKLY' | 'MONTHLY'; amount: number; currency: string; days: number };
type Subscription = { id:string; plan:string; amount:number; currency:string; status:string; startAt:string|null; endAt:string|null; createdAt:string; paymentId:string; paymentStatus:string|null; providerOrderId:string|null; description:string };
type Checkout = { subscriptionId:string; paymentId:string; keyId:string; orderId:string; amount:number; currency:string; description:string };
type RazorResponse = { razorpay_payment_id:string; razorpay_order_id:string; razorpay_signature:string };
async function loadCheckout(){if(window.Razorpay)return;await new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.async=true;script.onload=()=>resolve();script.onerror=()=>reject(new Error('Secure checkout could not be loaded.'));document.head.appendChild(script);});}
export default function SubscriptionPage(){
  const [items,setItems]=useState<Subscription[]>([]),[current,setCurrent]=useState<Subscription|null>(null),[plans,setPlans]=useState<Plan[]>([]),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const load=useCallback(async()=>{const result=await apiRequest<{items:Subscription[];current:Subscription|null;plans:Plan[];paymentsEnabled:boolean}>('/api/subscriptions');setItems(result.items);setCurrent(result.current);setPlans(result.plans);setEnabled(result.paymentsEnabled);},[]);
  useEffect(()=>{void load().catch(e=>setError(e.message||'Could not load subscription details.'));},[load]);
  async function buy(plan:Plan){setBusy(true);setError('');setNotice('');try{const {checkout}=await apiRequest<{checkout:Checkout}>('/api/subscriptions/checkout',{method:'POST',body:JSON.stringify({plan:plan.plan})});await loadCheckout();if(!window.Razorpay)throw new Error('Secure checkout is unavailable.');const modal=new window.Razorpay({key:checkout.keyId,amount:checkout.amount,currency:checkout.currency,name:'SkillSwap',description:checkout.description,order_id:checkout.orderId,handler:async(response:RazorResponse)=>{try{await apiRequest('/api/subscriptions/verify',{method:'POST',body:JSON.stringify({paymentId:checkout.paymentId,providerPaymentId:response.razorpay_payment_id,providerOrderId:response.razorpay_order_id,signature:response.razorpay_signature})});setNotice('Payment verified. Your subscription is active.');await load();}catch(e){setError(e instanceof Error?e.message:'Payment verification is pending.');}finally{setBusy(false);}},modal:{ondismiss:()=>setBusy(false)}});modal.on('payment.failed',()=>{setError('Payment was not completed. You can try again.');setBusy(false);});modal.open();}catch(e){setError(e instanceof Error?e.message:'Checkout could not be started.');setBusy(false);}}
  async function cancel(id:string){setBusy(true);setError('');try{await apiRequest(`/api/subscriptions/${encodeURIComponent(id)}/cancel`,{method:'POST'});setNotice('Pending checkout cancelled.');await load();}catch(e){setError(e instanceof Error?e.message:'Could not cancel pending checkout.');}finally{setBusy(false);}}
  return <main className="mx-auto max-w-5xl space-y-6"><Link to="/dashboard" className="text-sm font-semibold text-brand-700 hover:underline">← Dashboard</Link><header><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-600">Member access</p><h1 className="mt-2 text-3xl font-extrabold text-slate-900">Choose your subscription</h1><p className="mt-2 text-slate-600">A subscription is required to continue using your SkillSwap account. Payments are securely processed and verified by Razorpay.</p></header>{current?.status==='EXPIRED'&&<p role="status" className="rounded-xl bg-amber-50 p-4 font-semibold text-amber-900">Your subscription has expired.</p>}{error&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</p>}
    <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Current status</h2>{current?<div className="mt-3 flex flex-wrap justify-between gap-3"><div><p className="text-slate-700">{current.plan==='WEEKLY'?'Weekly':'Monthly'} · <strong>{current.status}</strong>{current.endAt?` · ends ${new Date(current.endAt).toLocaleString()}`:''}</p>{current.paymentId&&<Link to={`/payments?id=${encodeURIComponent(current.paymentId)}`} className="mt-2 inline-block text-sm font-semibold text-brand-700">View payment details</Link>}</div>{current.status==='PENDING'&&<button disabled={busy} onClick={()=>void cancel(current.id)} className="rounded-lg border px-3 py-2 text-sm font-semibold">Cancel pending checkout</button>}</div>:<p className="mt-2 text-sm text-slate-500">No active subscription yet.</p>}{current?.status==='ACTIVE'&&<Link to="/dashboard" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-brand-700 px-4 font-semibold text-white">Continue to Dashboard</Link>}</section>
    <section><h2 className="mb-3 text-lg font-bold">Available plans</h2><div className="grid gap-4 sm:grid-cols-2">{plans.map(plan=><article key={plan.plan} className="rounded-2xl border bg-white p-5"><h3 className="text-lg font-bold">{plan.plan==='WEEKLY'?'Weekly':'Monthly'}</h3><p className="mt-2 text-3xl font-extrabold">{paymentAmountLabel(plan.amount,plan.currency)}</p><p className="mt-1 text-sm text-slate-500">{plan.days} days</p><button disabled={!enabled||busy||current?.status==='ACTIVE'||current?.status==='PENDING'} onClick={()=>void buy(plan)} className="mt-4 min-h-11 w-full rounded-xl bg-brand-700 px-4 font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">{!enabled?'Checkout unavailable':busy?'Please wait…':current?.status==='ACTIVE'?'Already subscribed':current?.status==='PENDING'?'Checkout pending':'Subscribe securely'}</button></article>)}</div>{!enabled&&<p className="mt-3 text-sm text-slate-500">Checkout is currently unavailable. The server must be configured with Razorpay test credentials before test purchases can begin.</p>}</section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">Subscription history</h2>{items.length?<ul className="mt-3 divide-y">{items.map(item=><li key={item.id} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><span>{item.plan==='WEEKLY'?'Weekly':'Monthly'} · {new Date(item.createdAt||Date.now()).toLocaleDateString()}</span><span className="flex items-center gap-3">{paymentAmountLabel(item.amount,item.currency)} · {item.status}{item.paymentId&&<Link to={`/payments?id=${encodeURIComponent(item.paymentId)}`} className="font-semibold text-brand-700">Payment</Link>}</span></li>)}</ul>:<p className="mt-2 text-sm text-slate-500">Your plan history will appear here.</p>}</section>
  </main>;
}
