import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { apiRequest } from '../service/api';
import type { SwapRequest } from '../types';
import ReviewModal from '../components/reviews/ReviewModal';
import type { ReviewValues } from '../components/reviews/ReviewForm';
import ReportControl from '../components/admin/ReportControl';

type Action='accept'|'reject'|'start'|'cancel'|'complete';
const prompts:Record<Action,{title:string;body:string;button:string}>={accept:{title:'Accept this request?',body:'This creates a shared conversation so you can coordinate your exchange.',button:'Accept request'},reject:{title:'Decline this request?',body:'The requester will be notified that you declined.',button:'Decline request'},start:{title:'Start this exchange?',body:'Both members will be notified, and you can track completion here.',button:'Start exchange'},cancel:{title:'Cancel this exchange?',body:'The other member will be notified. This exchange cannot be restarted.',button:'Cancel exchange'},complete:{title:'Confirm you are finished?',body:'The exchange is complete after both members confirm.',button:'Confirm completion'}};
function Status({value}:{value:SwapRequest['status']}){return <span className="rounded-full bg-brand-50 px-3 py-1.5 text-sm font-bold text-brand-800">{value==='IN_PROGRESS'?'In progress':value.charAt(0)+value.slice(1).toLowerCase()}</span>}
export default function SwapRequestDetailsPage(){const {swapRequestId=''}=useParams();const [item,setItem]=useState<SwapRequest|null>(null),[viewer,setViewer]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState<Action|null>(null),[reviewOpen,setReviewOpen]=useState(false),[reviewType,setReviewType]=useState<'TEACHING'|'LEARNING'>('TEACHING');
  const refresh=useCallback(async()=>{const [result,session]=await Promise.all([apiRequest<{item:SwapRequest}>(`/api/swap-requests/${encodeURIComponent(swapRequestId)}`),apiRequest<{user:{id:string}}>('/api/auth/session')]);setItem(result.item);setViewer(session.user.id);},[swapRequestId]);
  useEffect(()=>{void refresh().catch(e=>setError(e.message||'Could not load this exchange.')).finally(()=>setLoading(false));},[refresh]);
  async function act(action:Action){if(!item)return;setBusy(true);setError('');try{const method=action==='complete'?'POST':'PATCH';await apiRequest(`/api/swap-requests/${encodeURIComponent(item.id)}/${action==='complete'?'confirm-completion':action}`,{method});setConfirm(null);await refresh();window.dispatchEvent(new Event('skillswap-notifications-changed'));}catch(e){setError(e instanceof Error?e.message:'Could not update this exchange.');}finally{setBusy(false);}}
  async function review(values:ReviewValues){if(!item)return;const revieweeId=item.senderId===viewer?item.receiverId:item.senderId;const type=values.reviewType,id=type==='TEACHING'?item.myTeachingReviewId:item.myLearningReviewId;await apiRequest(id?`/api/reviews/${encodeURIComponent(id)}`:'/api/reviews',{method:id?'PATCH':'POST',body:JSON.stringify(id?values:{...values,revieweeId,swapRequestId:item.id})});await refresh();window.dispatchEvent(new Event('skillswap-notifications-changed'));}
  if(loading)return <main className="mx-auto max-w-3xl py-12 text-center text-slate-500">Loading exchange…</main>;
  if(!item)return <main className="mx-auto max-w-3xl rounded-2xl border bg-white p-8 text-center"><h1 className="text-xl font-bold">Exchange not found</h1><p role="alert" className="mt-2 text-sm text-slate-600">{error||'This exchange is unavailable.'}</p><Link className="mt-4 inline-block font-semibold text-brand-700" to="/swap-requests">Back to swap requests</Link></main>;
  const sent=viewer===item.senderId,ownConfirmed=sent?item.senderCompletedAt:item.receiverCompletedAt,otherConfirmed=sent?item.receiverCompletedAt:item.senderCompletedAt,peerName=sent?item.receiverName:item.senderName,requester=item.direction==='SENT'?`You proposed teaching ${item.skillOffered} and learning ${item.skillWanted}.`:`${item.senderName} proposed teaching ${item.skillOffered} and learning ${item.skillWanted}.`;
  const timeline=[['Request sent',item.createdAt],['Accepted',item.acceptedAt],['Exchange started',item.startedAt],['Completed',item.completedAt]].filter((entry):entry is [string,string]=>!!entry[1]);
  return <main className="mx-auto max-w-3xl"><Link to="/swap-requests" className="text-sm font-semibold text-brand-700 hover:underline">← All swap requests</Link>{error&&<p role="alert" className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<article className="mt-4 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 bg-gradient-to-r from-brand-50 to-white p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-600">Skill exchange</p><h1 className="mt-2 text-2xl font-extrabold text-slate-900 sm:text-3xl">{peerName}</h1></div><Status value={item.status}/></div><p className="mt-5 text-lg font-semibold text-slate-800">{item.skillOffered} <span className="text-brand-600">↔</span> {item.skillWanted}</p><p className="mt-2 text-sm text-slate-600">{requester}</p>{item.message&&<blockquote className="mt-4 rounded-xl border border-slate-100 bg-white/80 p-4 text-sm text-slate-600">“{item.message}”</blockquote>}</div>
    <div className="grid gap-8 p-6 sm:grid-cols-2 sm:p-8"><section><h2 className="font-bold text-slate-900">Exchange timeline</h2><ol className="mt-4 space-y-4">{timeline.map(([label,date])=><li key={label} className="flex gap-3"><span className="mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full bg-brand-600"/><div><p className="text-sm font-semibold text-slate-800">{label}</p><time className="text-xs text-slate-500">{new Date(date).toLocaleString()}</time></div></li>)}{item.status==='IN_PROGRESS'&&!item.completedAt&&<li className="flex gap-3"><span className="mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full bg-amber-400"/><p className="text-sm text-slate-600">{ownConfirmed?'You confirmed completion':'Waiting for your confirmation'}{otherConfirmed?' · the other member confirmed':''}</p></li>}</ol></section><section><h2 className="font-bold text-slate-900">Next step</h2><p className="mt-2 text-sm leading-6 text-slate-600">Keep your plans in the shared conversation. Once you have finished, confirm here. The exchange is marked complete after you both confirm.</p>{item.conversationId&&<Link to={`/messages/${encodeURIComponent(item.conversationId)}`} className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-xl border border-brand-200 px-4 text-sm font-semibold text-brand-800 hover:bg-brand-50">Open exchange chat</Link>}</section></div>
    <div className="flex flex-wrap items-center gap-2 border-t border-slate-100 p-6 sm:px-8">{item.status==='PENDING'&&item.direction==='RECEIVED'&&<><button onClick={()=>setConfirm('accept')} className="min-h-11 rounded-xl bg-brand-700 px-5 text-sm font-bold text-white">Accept request</button><button onClick={()=>setConfirm('reject')} className="min-h-11 rounded-xl border border-slate-200 px-5 text-sm font-semibold text-slate-700">Decline</button></>}{item.status==='ACCEPTED'&&<button onClick={()=>setConfirm('start')} className="min-h-11 rounded-xl bg-brand-700 px-5 text-sm font-bold text-white">Start exchange</button>}{item.status==='IN_PROGRESS'&&!ownConfirmed&&<button onClick={()=>setConfirm('complete')} className="min-h-11 rounded-xl bg-emerald-700 px-5 text-sm font-bold text-white">Confirm exchange complete</button>}{item.status==='IN_PROGRESS'&&ownConfirmed&&!item.completedAt&&<span className="inline-flex min-h-11 items-center rounded-xl bg-amber-50 px-4 text-sm font-semibold text-amber-900">Waiting for {peerName} to confirm</span>}{['PENDING','ACCEPTED','IN_PROGRESS'].includes(item.status)&&<button onClick={()=>setConfirm('cancel')} className="min-h-11 rounded-xl border border-rose-200 px-5 text-sm font-semibold text-slate-700">Cancel exchange</button>}{item.status==='COMPLETED'&&<><button onClick={()=>{setReviewType('TEACHING');setReviewOpen(true)}} className="min-h-11 rounded-xl bg-brand-700 px-5 text-sm font-bold text-white">{item.myTeachingReviewId?'Edit teaching review':'Review teaching'}</button><button onClick={()=>{setReviewType('LEARNING');setReviewOpen(true)}} className="min-h-11 rounded-xl border border-brand-200 px-5 text-sm font-bold text-brand-800">{item.myLearningReviewId?'Edit learning review':'Review learning'}</button></>}<ReportControl targetType="SWAP" targetId={item.id}/></div>
    </article>
    {confirm&&<div role="presentation" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><section role="alertdialog" aria-modal="true" aria-labelledby="confirm-title" className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><h2 id="confirm-title" className="text-lg font-bold text-slate-900">{prompts[confirm].title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{prompts[confirm].body}</p><div className="mt-6 flex justify-end gap-2"><button disabled={busy} onClick={()=>setConfirm(null)} className="min-h-10 rounded-lg border border-slate-200 px-4 text-sm font-semibold">Go back</button><button disabled={busy} onClick={()=>void act(confirm)} className={`min-h-10 rounded-lg px-4 text-sm font-bold text-white ${confirm==='reject'||confirm==='cancel'?'bg-rose-600':'bg-brand-700'}`}>{busy?'Please wait…':prompts[confirm].button}</button></div></section></div>}
    <ReviewModal key={`${reviewType}:${reviewType==='TEACHING'?item.myTeachingReviewId||'new':item.myLearningReviewId||'new'}`} open={reviewOpen} onClose={()=>setReviewOpen(false)} onSubmit={review} initial={reviewType==='TEACHING'?(item.myTeachingReviewId?{rating:item.myReviewRating||0,comment:item.myReviewComment||'',reviewType}:undefined):item.myLearningReviewId?{rating:item.myLearningReviewRating||0,comment:item.myLearningReviewComment||'',reviewType}:undefined} title={`${reviewType==='TEACHING'?'Teaching':'Learning'} review with ${peerName}`}/>
  </main>;
}
