import { useState } from 'react';
import RatingStars from './RatingStars';
import type { ReviewValues } from './ReviewForm';
export type Review = { id:string;reviewerId:string;reviewerName:string;reviewerAvatar:string|null;revieweeId:string;swapRequestId:string;rating:number;comment:string;reviewType:'TEACHING'|'LEARNING';createdAt:string;updatedAt:string;skillOffered?:string;skillWanted?:string };
export default function ReviewCard({ review, canEdit = false, onEdit, onDelete }: { review:Review;canEdit?:boolean;onEdit?:(values:ReviewValues)=>void;onDelete?:(id:string)=>void }) {
  const [confirm,setConfirm]=useState(false);const initials=review.reviewerName.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();const date=new Date(review.createdAt).toLocaleDateString([],{year:'numeric',month:'short',day:'numeric'});
  return <article className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-full bg-brand-100 text-sm font-bold text-brand-800">{review.reviewerAvatar?<img src={review.reviewerAvatar} alt="" className="h-full w-full object-cover"/>:initials}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-x-4 gap-y-1"><h3 className="font-bold text-slate-900">{review.reviewerName}</h3><time dateTime={review.createdAt} className="text-xs text-slate-400">{date}</time></div><span className="mt-1 inline-flex rounded-full bg-brand-50 px-2 py-0.5 text-xs font-semibold text-brand-800">{review.reviewType==='LEARNING'?'Learning':'Teaching'} review</span><RatingStars value={review.rating} size="sm" label={`${review.rating} out of 5 stars`}/>{(review.skillOffered||review.skillWanted)&&<p className="mt-1 text-xs text-slate-500">{review.skillOffered||'Skill'} ↔ {review.skillWanted||'Skill'} exchange</p>}</div></div>{review.comment&&<p className="mt-4 whitespace-pre-wrap break-words text-sm leading-6 text-slate-700">{review.comment}</p>}
    {canEdit&&<div className="mt-3 flex flex-wrap gap-3">{onEdit&&<button onClick={()=>onEdit({rating:review.rating,comment:review.comment,reviewType:review.reviewType})} className="text-sm font-semibold text-brand-700 hover:underline">Edit Review</button>}{onDelete&&!confirm&&<button onClick={()=>setConfirm(true)} className="text-sm font-semibold text-rose-600 hover:underline">Delete Review</button>}</div>}
    {confirm&&<div role="alertdialog" aria-label="Delete Review?" className="mt-3 rounded-xl border border-rose-100 bg-rose-50 p-3"><p className="font-semibold text-slate-900">Delete Review?</p><p className="mt-1 text-sm text-slate-600">This action cannot be undone.</p><div className="mt-3 flex justify-end gap-2"><button onClick={()=>setConfirm(false)} className="rounded-lg border bg-white px-3 py-1.5 text-sm font-semibold">Cancel</button><button onClick={()=>onDelete?.(review.id)} className="rounded-lg bg-rose-600 px-3 py-1.5 text-sm font-semibold text-white">Delete</button></div></div>}</article>;
}
