import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiRequest } from '../../service/api';
import type { RecommendedSkill, RecommendedUser } from '../../types';
import { useRealtimeEvent } from '../../realtime/events';

type Props={mode?:'all'|'users'|'skills'; title?:string};
type Result<T>={items:T[];source:'deterministic'|'hybrid';limited?:boolean};
function RecommendationScore({value}:{value:number}){return <span className="shrink-0 rounded-full bg-brand-50 px-2.5 py-1 text-xs font-semibold text-brand-800">{value}% skill match</span>}
function RecommendationReason({reasons}:{reasons:string[]}){return <details className="mt-3 text-sm"><summary className="cursor-pointer font-semibold text-brand-700">Why this recommendation?</summary><ul className="mt-2 list-disc space-y-1 pl-5 text-slate-600">{reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></details>}
function RecommendationFeedback({targetType,targetId,onDone}:{targetType:'USER'|'SKILL';targetId:string;onDone:()=>void}){
  const [value,setValue]=useState('');
  async function choose(feedback:'INTERESTED'|'NOT_INTERESTED'){try{await apiRequest('/api/recommendations/feedback',{method:'POST',body:JSON.stringify({targetType,targetId,feedback})});setValue(feedback);if(feedback==='NOT_INTERESTED')onDone()}catch{setValue('Unable to save feedback. Try again.')}}
  return <div className="mt-3 flex items-center gap-2 text-xs"><span className="text-slate-500">Useful?</span><button onClick={()=>void choose('INTERESTED')} className="rounded-lg border px-2.5 py-1.5 font-semibold text-slate-700 hover:bg-slate-50">Interested</button><button onClick={()=>void choose('NOT_INTERESTED')} className="rounded-lg border px-2.5 py-1.5 font-semibold text-slate-700 hover:bg-slate-50">Not interested</button>{value&&value!=='INTERESTED'&&<span role="status" className="text-slate-500">{value}</span>}</div>
}
function RecommendedUserCard({item,onRemove}:{item:RecommendedUser;onRemove:()=>void}){
  return <article className="rounded-xl border border-slate-100 p-4"><div className="flex items-start justify-between gap-3"><div><Link to={`/profile/${encodeURIComponent(item.user.id)}`} className="font-bold text-slate-900 hover:text-brand-700">{item.user.name}</Link><p className="mt-1 text-sm text-slate-600">Teaches {item.relevantSkill?.name||item.teaches[0]?.name||'skills from your learning profile'}</p>{item.rating?.totalReviews? <p className="mt-1 text-xs text-amber-700">Teaching ★ {item.rating.averageRating.toFixed(1)} · {item.rating.totalReviews} visible teaching review{item.rating.totalReviews===1?'':'s'}</p>:null}{item.availabilityCompatibility&&<p className="mt-1 text-xs font-semibold text-emerald-700">✓ Listed availability overlaps</p>}</div><RecommendationScore value={item.matchScore}/></div><RecommendationReason reasons={item.reasons}/><Link to={`/profile/${encodeURIComponent(item.user.id)}`} className="mt-3 inline-flex min-h-9 items-center rounded-lg border px-3 text-sm font-semibold text-slate-700">View profile</Link><RecommendationFeedback targetType="USER" targetId={item.user.id} onDone={onRemove}/></article>
}
function RecommendedSkillCard({item,onRemove}:{item:RecommendedSkill;onRemove:()=>void}){
  return <article className="rounded-xl border border-slate-100 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-slate-900">{item.name}</h3><p className="text-sm text-brand-700">{item.category}</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-800">Suggested skill</span></div><p className="mt-2 text-sm text-slate-600">{item.reason}</p>{item.teachers>0&&<p className="mt-2 text-xs text-slate-500">{item.teachers} active {item.teachers===1?'teacher':'teachers'} listed</p>}<Link to={`/skills/${encodeURIComponent(item.skillId)}`} className="mt-3 inline-flex min-h-9 items-center rounded-lg border px-3 text-sm font-semibold text-slate-700">Explore skill</Link><RecommendationFeedback targetType="SKILL" targetId={item.skillId} onDone={onRemove}/></article>
}
function RecommendationSkeleton(){return <div role="status" className="grid gap-3 md:grid-cols-2"><span className="sr-only">Finding relevant matches…</span>{[1,2].map(id=><div key={id} className="h-32 animate-pulse rounded-xl bg-slate-100"/> )}</div>}
function RecommendationEmptyState(){return <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No new recommendations right now. Add skills or learning goals to improve suggestions.</p>}

export default function RecommendationSection({mode='all',title='Recommended for You'}:Props){
  const [users,setUsers]=useState<RecommendedUser[]>([]),[skills,setSkills]=useState<RecommendedSkill[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);
  useRealtimeEvent(['NOTIFICATION_CREATED','CONNECTION_READY'],event=>{const note=event.notification as {type?:string}|undefined;if(event.type==='CONNECTION_READY'||note?.type==='NEW_MATCH')setRevision(value=>value+1);});
  useEffect(()=>{let live=true;setLoading(true);setError('');const jobs:Promise<void>[]=[];if(mode!=='skills')jobs.push(apiRequest<Result<RecommendedUser>>('/api/recommendations/users?limit=4').then(r=>{if(live)setUsers(r.items)}));if(mode!=='users')jobs.push(apiRequest<Result<RecommendedSkill>>('/api/recommendations/skills?limit=4').then(r=>{if(live)setSkills(r.items)}));Promise.allSettled(jobs).then(results=>{if(live&&results.some(x=>x.status==='rejected'))setError('Some smart recommendations are temporarily unavailable.');if(live)setLoading(false)});return()=>{live=false}},[mode,revision]);
  if(loading)return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-4 text-lg font-bold">{title}</h2><RecommendationSkeleton/></section>;
  return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-lg font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">Skill suggestions based on your profile. Recommendations are optional.</p></div>{mode==='all'&&<Link to="/matches" className="text-sm font-semibold text-brand-700">Explore matches</Link>}</div>{error&&<p role="status" className="mt-3 text-sm text-slate-500">{error} Showing any available deterministic recommendations.</p>}{!users.length&&!skills.length?<div className="mt-4"><RecommendationEmptyState/></div>:<div className="mt-4 grid gap-4 lg:grid-cols-2">{users.map(item=><RecommendedUserCard key={item.user.id} item={item} onRemove={()=>setUsers(list=>list.filter(x=>x.user.id!==item.user.id))}/>)}{skills.map(item=><RecommendedSkillCard key={item.skillId} item={item} onRemove={()=>setSkills(list=>list.filter(x=>x.skillId!==item.skillId))}/>)}</div>}</section>
}
